---
title: "Random Intercept, Random Slope"
author: "Suzanne Dufault"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      fig.path = "../graphs/simulation-results/random-intercept-random-slope/")

library(tidyverse)
library(patchwork)
library(jpeg) # https://www.geeksforgeeks.org/how-to-add-image-to-ggplot2-in-r/
library(here)
library(kableExtra)
library(latex2exp)
library(furrr)
library(patchwork)
source(here("lib", "ucsf-color-palette.R"))
options(knitr.kable.NA = '')
source(here("lib", "target-product-profile-function.R"))
source(here("lib", "mcmc-rank-function.R"))
source(here("lib", "mcmc-compare-v-control.R"))
```

# Output {.tabset}

## Settings

```{r lineplot-simulating-ttp}
# Call in model being used as "truth"
load("~/Library/CloudStorage/OneDrive-UCSF/ucsf-research/phase2b-simstudy/data/bayes-generated/2021-12-14_remox-lmm-short.RData")

# Pull out coefficients
s <- summary(fit.cens)
betas_orig <- c(s$fixed$Estimate)

p0 <- data.frame(Control = betas_orig[1] + betas_orig[2]*0:8,
           Regimen1 = betas_orig[1] + betas_orig[2]*0:8 + betas_orig[3]*0:8,
           Regimen2 = betas_orig[1] + betas_orig[2]*0:8 + betas_orig[4]*0:8,
           weeks = 0:8) %>% 
  pivot_longer(cols = 1:3,
               values_to = "log10(TTP)",
               names_to = "Regimen") %>% 
  ggplot(aes(x = weeks, y = 10^(`log10(TTP)`), col = Regimen)) + 
  geom_line() + 
  scale_y_log10("TTP in days, log10 scale",
                breaks = c(5,7,10,15,20,25,35),
                labels = c(5,7,10,15,20,25,35)) + 
  scale_x_continuous("Days from randomization",
                     breaks = 0:8,
                     labels = seq(0,56, by = 7)) + 
  scale_color_manual(values = ucsf_col_pal,
                     labels = c(1:3)) +
  scale_linetype_discrete(labels = c(1:3)) +
  coord_cartesian(ylim = c(7,35)) + 
  ggtitle("Original REMoxTB data",
          subtitle = "Linear Bayesian hierarchical model") + 
  theme_bw()

betas_orig <- c(s$fixed$Estimate)[1:2] # (just the intercept and control group slope for now)

slopes_even <- seq(0.1,0.4,by = 0.1)
beta_Regimens <- betas_orig[2]*slopes_even # multiplying the control group slope by the a priori %change
betas <- c(betas_orig, beta_Regimens) # length k+1 (intercept + slopes per K Regimens)

p1 <- data.frame(Control = betas[1] + betas[2]*0:8,
           Regimen1 = betas[1] + betas[2]*0:8 + betas[3]*0:8,
           Regimen2 = betas[1] + betas[2]*0:8 + betas[4]*0:8,
           Regimen3 = betas[1] + betas[2]*0:8 + betas[5]*0:8,
           Regimen4 = betas[1] + betas[2]*0:8 + betas[6]*0:8,
           weeks = 0:8) %>% 
  pivot_longer(cols = 1:5,
               values_to = "log10(TTP)",
               names_to = "Regimen") %>% 
  ggplot(aes(x = weeks, y = 10^(`log10(TTP)`), col = Regimen, lty = Regimen)) + 
  geom_line() + 
  scale_y_log10("TTP in days, log10 scale",
                breaks = c(5,7,10,15,20,25,35),
                labels = c(5,7,10,15,20,25,35)) + 
  scale_x_continuous("Days from randomization",
                     breaks = 0:8,
                     labels = seq(0,56, by = 7)) + 
  scale_color_manual(values = ucsf_col_pal,
                     labels = c(1:5)) +
  scale_linetype_discrete(labels = c(1:5)) +
  coord_cartesian(ylim = c(7,35)) + 
  ggtitle("1 Winner condition", subtitle = c("10%, 20%, 30%, 40%")) + 
  theme_bw()

slopes_highlow <- c(-.1, .1, .35, .4)
beta_Regimens <- betas_orig[2]*slopes_highlow # multiplying the control group slope by the a priori %change
betas <- c(betas_orig, beta_Regimens) # length k+1 (intercept + slopes per K Regimens)

p2 <- data.frame(Control = betas[1] + betas[2]*0:8,
           Regimen1 = betas[1] + betas[2]*0:8 + betas[3]*0:8,
           Regimen2 = betas[1] + betas[2]*0:8 + betas[4]*0:8,
           Regimen3 = betas[1] + betas[2]*0:8 + betas[5]*0:8,
           Regimen4 = betas[1] + betas[2]*0:8 + betas[6]*0:8,
           weeks = 0:8) %>% 
  pivot_longer(cols = 1:5,
               values_to = "log10(TTP)",
               names_to = "Regimen") %>% 
  ggplot(aes(x = weeks, y = 10^(`log10(TTP)`), col = Regimen, lty = Regimen)) + 
  geom_line() + 
  scale_y_log10("TTP in days, log10 scale",
                breaks = c(5,7,10,15,20,25,35),
                labels = c(5,7,10,15,20,25,35)) + 
  scale_x_continuous("Days from randomization",
                     breaks = 0:8,
                     labels = seq(0,56, by = 7)) +
  scale_color_manual(values = ucsf_col_pal,
                     labels = c(1:5)) +
  scale_linetype_discrete(labels = c(1:5)) +
  coord_cartesian(ylim = c(7,35)) + 
  ggtitle("2 Winners condition", subtitle = c("-10%, 10%, 35%, 40%")) + 
  theme_bw()

slopes_high <- c(.35, .37, .39, .41)
beta_Regimens <- betas_orig[2]*slopes_high # multiplying the control group slope by the a priori %change
betas <- c(betas_orig, beta_Regimens) # length k+1 (intercept + slopes per K Regimens)

p3 <- data.frame(Control = betas[1] + betas[2]*0:8,
           Regimen1 = betas[1] + betas[2]*0:8 + betas[3]*0:8,
           Regimen2 = betas[1] + betas[2]*0:8 + betas[4]*0:8,
           Regimen3 = betas[1] + betas[2]*0:8 + betas[5]*0:8,
           Regimen4 = betas[1] + betas[2]*0:8 + betas[6]*0:8,
           weeks = 0:8) %>% 
  pivot_longer(cols = 1:5,
               values_to = "log10(TTP)",
               names_to = "Regimen") %>% 
  ggplot(aes(x = weeks, y = 10^(`log10(TTP)`), col = Regimen, lty = Regimen)) + 
  geom_line() + 
  scale_y_log10("TTP in days, log10 scale",
                breaks = c(5,7,10,15,20,25,35),
                labels = c(5,7,10,15,20,25,35)) + 
  scale_x_continuous("Days from randomization",
                     breaks = 0:8,
                     labels = seq(0,56, by = 7)) + 
  scale_color_manual(values = ucsf_col_pal,
                     labels = c(1:5)) +
  scale_linetype_discrete(labels = c(1:5)) +
  coord_cartesian(ylim = c(7,35)) + 
  ggtitle("4 Winners condition", subtitle = c("35%, 37%, 39%, 41%")) + 
  theme_bw()

ttp_fig <- gridExtra::grid.arrange(p0,p1,p2,p3)
```

```{r fig.width=10, fig.height=5}
library(magick)
survival_fig <- image_ggplot(image_read(here("graphs", "simulation-settings","2022-03-22_survival-curve-general.jpg")))
ggpubr::ggarrange(ttp_fig, survival_fig,
                  widths = c(3,2),
                  labels = "AUTO",
                  heights = 1)
```

```{r eval = FALSE}
ggsave(filename = here("graphs", "simulation-settings",
                       paste0(Sys.Date(), "_ttp-relapse-simulation-settings.jpeg")),
       device = "jpeg",
       units = "in",
       width = 10,
       height = 5)
```

## Unfavorable Outcome 

```{r relapse-data}
# Situation 1, S(52) = .95
load(here("data","analyzed","2023-08-16_s95-situation1-results_nk20_4mo-duration.RData"))
s95.sit1.20 <- rename(s95.sit1.20, n_relapse_interim1 = n_relapses)
load(here("data","analyzed","2022-03-07_s95-situation1-results_nk30_4mo-duration.RData"))
s95.sit1.30 <- s95.situation1.results
load(here("data","analyzed","2022-03-07_s95-situation1-results_nk40_4mo-duration.RData"))
s95.sit1.40 <- s95.situation1.results
load(here("data","analyzed","2022-03-07_s95-situation1-results_nk60_4mo-duration.RData"))
s95.sit1.60 <- s95.situation1.results
load(here("data","analyzed","2022-03-07_s95-situation1-results_nk80_4mo-duration.RData"))
s95.sit1.80 <- s95.situation1.results; rm(s95.situation1.results)
```

```{r fig-relapse-data, fig.width = 7, fig.height = 9}
bind_rows(mutate(s95.sit1.20, nk = 20),
          mutate(s95.sit1.30, nk = 30),
          mutate(s95.sit1.40, nk = 40),
          mutate(s95.sit1.60, nk = 60),
          mutate(s95.sit1.80, nk = 80)) %>% 
  group_by(nk, regimen) %>% 
  summarise(prop_stopped_1 = mean(n_relapse_interim1 >= 1),
            prop_stopped_2 = mean(n_relapse_interim1 >= 2),
            prop_stopped_3 = mean(n_relapse_interim1 >= 3),
            prop_stopped_4 = mean(n_relapse_interim1 >= 4),
            prop_stopped_5 = mean(n_relapse_interim1 >= 5)) %>% 
  ungroup() %>% 
  pivot_longer(cols = prop_stopped_1:prop_stopped_5,
               names_to = "threshold",
               values_to = "prop_stopped") %>% 
  filter(!regimen %in%  c(1,3)) %>% #removing control and one of the minimal regimens
  mutate(rate = case_when(regimen == 2 ~ "Sub-optimal: 10% Unfavorable Outcome Rate",
                          regimen == 4 ~ "Minimal: 5% Unfavorable Outcome Rate",
                          regimen == 5 ~ "Desirable: 2.5% Unfavorable Outcome Rate"),
         threshold = str_remove(threshold, "prop_stopped_")) %>% 
  mutate(rate = factor(rate, levels = c("Sub-optimal: 10% Unfavorable Outcome Rate","Minimal: 5% Unfavorable Outcome Rate","Desirable: 2.5% Unfavorable Outcome Rate"))) %>% 
  ggplot(aes(x = as.factor(nk),
             y = threshold, 
             # shape = threshold, 
             fill = prop_stopped)) + 
  facet_wrap(~rate, ncol = 1) + 
  geom_tile() + 
  geom_text(aes(label = format(round(prop_stopped, 2), nsmall = 2)),
            col = "white") +
  ggpubr::theme_pubr() + 
  scale_y_discrete("Unfavorable outcome threshold") +
  scale_x_discrete(TeX("$n_k$"), breaks = c(20,30,40,60,80), labels = c(20,30,40,60,80)) + 
  scale_fill_viridis_c(TeX("Pr(No. observed unfavorable outcomes $\\geq$ threshold)")) + 
  theme(legend.position = "bottom")
```

```{r eval= FALSE}
ggsave(filename = here("graphs", "simulation-results", "random-intercept-random-slope",
                       paste0(Sys.Date(), "_relapse-thresholds.jpg")),
       device = "jpg",
       height = 6,
       width = 5.5,
       units = "in")

ggsave(filename = here("graphs", "submission", "fig-03_relapse-thresholds.eps"),
       device = "eps",
       height = 6,
       width = 6,
       units = "in")
```

```{r eval = FALSE}
bind_rows(mutate(s95.sit1.20, nk = 20),
          mutate(s95.sit1.30, nk = 30),
          mutate(s95.sit1.40, nk = 40),
          mutate(s95.sit1.60, nk = 60),
          mutate(s95.sit1.80, nk = 80)) %>% 
  group_by(nk, regimen) %>% 
  summarise(prop_stopped_1 = mean(n_relapse_interim1 >= 1),
            prop_stopped_2 = mean(n_relapse_interim1 >= 2),
            prop_stopped_3 = mean(n_relapse_interim1 >= 3),
            prop_stopped_4 = mean(n_relapse_interim1 >= 4),
            prop_stopped_5 = mean(n_relapse_interim1 >= 5)) %>% 
  ungroup() %>% 
  pivot_longer(cols = prop_stopped_1:prop_stopped_5,
               names_to = "threshold",
               values_to = "prop_stopped") %>% 
  filter(!regimen %in%  c(1,3)) %>% #removing control and one of the minimal regimens
  mutate(rate = case_when(regimen == 2 ~ "Sub-optimal: 10% Unfavorable Outcome Rate",
                          regimen == 4 ~ "Minimal: 5% Unfavorable Outcome Rate",
                          regimen == 5 ~ "Desirable: 2.5% Unfavorable Outcome Rate"),
         threshold = str_remove(threshold, "prop_stopped_")) %>% 
  mutate(rate = factor(rate, levels = c("Sub-optimal: 10% Unfavorable Outcome Rate","Minimal: 5% Unfavorable Outcome Rate","Desirable: 2.5% Unfavorable Outcome Rate"))) %>% 
  ggplot(aes(x = as.factor(nk),
             y = threshold, 
             # shape = threshold, 
             fill = prop_stopped)) + 
  ggtitle("Dufault Fig 3. (Top)") +
  facet_wrap(~rate, ncol = 1) + 
  geom_tile() + 
  geom_text(aes(label = format(round(prop_stopped, 2), nsmall = 2)),
            col = "white") +
  ggpubr::theme_pubr() + 
  scale_y_discrete("Unfavorable outcome threshold") +
  scale_x_discrete(TeX("$n_k$"), breaks = c(20,30,40,60,80), labels = c(20,30,40,60,80)) + 
  scale_fill_viridis_c(TeX("Pr(No. observed unfavorable outcomes $\\geq$ threshold)")) + 
  theme(legend.position = "bottom")

ggsave(filename = here("graphs", "submission", "fig-03_relapse-thresholds_annotated.eps"),
       device = "eps",
       dpi = 600,
       height = 6,
       width = 6,
       units = "in")
```

## TTP {.tabset .tabset-pills}

### Target Product Profile Decisions

```{r tpp-decision-function}
# generated by analysis/03_tpp-decisions.R
load(here("data", "analyzed", "target-product-profile", "2022-07-07_tpp-decisions.RData"))
```

```{r}
d_hl <- decisions$decisions_highlow %>% 
  filter(Regimen == "Regimen 1") %>% 
  mutate(Regimen = case_when(Regimen == "Regimen 1" ~ "-10%"))
d_full <- decisions$decisions_even %>% 
  mutate(Regimen = case_when(Regimen == "Regimen 1" ~ "10%",
                             Regimen == "Regimen 2" ~ "20%",
                             Regimen == "Regimen 3" ~ "30%",
                             Regimen == "Regimen 4" ~ "40%")) %>% 
  bind_rows(d_hl) %>%
  mutate(Decision = factor(Decision, levels = c("NO-GO", "Continue", "GO")),
         nk = factor(nk)) %>% 
  group_by(Regimen, nk, Decision) %>% 
  summarise(n = n_distinct(sim)) %>% 
  group_by(Regimen, nk) %>% 
  summarise(Probability = n/sum(n),
            Decision = Decision) 

d_full %>% 
  ungroup() %>% 
  pivot_wider(values_from = Probability,
              names_from = Decision) %>% 
  dplyr::select(-Regimen) %>% 
  kable(digits = 2,
        caption = "Decision percentages when tau_MAV = tau_TV = 0.025") %>% 
  kable_styling() %>% 
  group_rows("Slope, %: -10%", start_row = 1, end_row = 5) %>% 
  group_rows("Slope, %: 10%", start_row = 6, end_row = 10) %>%
  group_rows("Slope, %: 20%", start_row = 11, end_row = 15) %>% 
  group_rows("Slope, %: 30%", start_row = 16, end_row = 20) %>% 
  group_rows("Slope, %: 40%", start_row = 21, end_row = 25)
```

```{r barplot-tpp-decisions, fig.width = 10, fig.height = 6, fig.cap = "When theta_mav = 0, theta_TV = 20, tau_mav = tau_TV = 0.025."}
d_full %>% 
  ggplot(aes(x = nk, y = Probability, fill = Decision)) + 
  geom_bar(stat = "identity") + 
  facet_wrap(~Regimen, nrow = 1) +
  scale_y_continuous("Decision Probability",
                     breaks = seq(0,1,by = 0.1),
                     labels = seq(0,1,by = 0.1)) +
  scale_fill_manual(values = c("red", ucsf_col_pal[8], ucsf_col_pal[4]),
                    breaks = c("NO-GO", "Continue", "GO"),
                    labels = c("NO-GO", "Continue", "GO")) +
  xlab(TeX("$n_k$")) + 
  # ggtitle("", subtitle = TeX("$\\theta_{MAV} = 0%, \\theta_{TV} = 20%, \\tau_{MAV} = \\tau_{TV} = 0.025$")) +
  ggpubr::theme_pubr() + 
  theme(legend.position = "bottom")
```

```{r eval=FALSE}
ggsave(filename = here("graphs", "submission", "fig-04_barplot-tpp-decisions.eps"),
       device = "eps",
       height = 6,
       width = 9,
       units = "in")
```

```{r eval = FALSE}
d_full %>% 
  ggplot(aes(x = nk, y = Probability, fill = Decision)) + 
  geom_bar(stat = "identity") + 
  facet_wrap(~Regimen, nrow = 1) +
  scale_y_continuous("Decision Probability",
                     breaks = seq(0,1,by = 0.1),
                     labels = seq(0,1,by = 0.1)) +
  scale_fill_manual(values = c("red", ucsf_col_pal[8], ucsf_col_pal[4]),
                    breaks = c("NO-GO", "Continue", "GO"),
                    labels = c("NO-GO", "Continue", "GO")) +
  xlab(TeX("$n_k$")) + 
  ggtitle("Dufault Fig. 4 (Top)") +
  # ggtitle("", subtitle = TeX("$\\theta_{MAV} = 0%, \\theta_{TV} = 20%, \\tau_{MAV} = \\tau_{TV} = 0.025$")) +
  ggpubr::theme_pubr() + 
  theme(legend.position = "bottom")

ggsave(filename = here("graphs", "submission", "fig-04_barplot-tpp-decisions_annotated.eps"),
       device = "eps",
       dpi = 600,
       height = 6,
       width = 9,
       units = "in")
```

<!-- # ```{r decisions-2, cache = TRUE} -->
<!-- # plan(multisession) -->
<!-- # nk <- as.list(c(20,30,40,60,80)) -->
<!-- # names(nk) <- nk -->
<!-- # decisions_2 <- future_map2_dfr(mcmc_even, nk, ~decision_function(.x, -->
<!-- #                                                                nk = .y, -->
<!-- #                                                                theta_mav = 0, # in % -->
<!-- #                                                                theta_tv = 20, # in %  -->
<!-- #                                                                tau_mav = 0.05,  -->
<!-- #                                                                tau_tv = 0.05)) -->
<!-- #  -->
<!-- # decisions_highlow_2 <- future_map2_dfr(mcmc_highlow, nk, ~decision_function(.x, -->
<!-- #                                                                           nk = .y, -->
<!-- #                                                                           theta_mav = 0, # in % -->
<!-- #                                                                           theta_tv = 20, # in %  -->
<!-- #                                                                           tau_mav = 0.05,  -->
<!-- #                                                                           tau_tv = 0.05)) -->
<!-- # ``` -->

<!-- ```{r} -->
<!-- d_hl_2 <- decisions_highlow_2 %>% -->
<!--   filter(Regimen == "Regimen 1") %>% -->
<!--   mutate(Regimen = case_when(Regimen == "Regimen 1" ~ "-10%")) -->
<!-- d_full_2 <- decisions_2 %>% -->
<!--   mutate(Regimen = case_when(Regimen == "Regimen 1" ~ "10%", -->
<!--                              Regimen == "Regimen 2" ~ "20%", -->
<!--                              Regimen == "Regimen 3" ~ "30%", -->
<!--                              Regimen == "Regimen 4" ~ "40%")) %>% -->
<!--   bind_rows(d_hl) %>% -->
<!--   mutate(Decision = factor(Decision, levels = c("NO-GO", "Continue", "GO")), -->
<!--          nk = factor(nk)) %>% -->
<!--   group_by(Regimen, nk, Decision) %>% -->
<!--   summarise(n = n_distinct(sim)) %>% -->
<!--   group_by(Regimen, nk) %>% -->
<!--   summarise(Probability = n/sum(n), -->
<!--             Decision = Decision) -->

<!-- d_full_2 %>% -->
<!--   ungroup() %>% -->
<!--   pivot_wider(values_from = Probability, -->
<!--               names_from = Decision) %>% -->
<!--   dplyr::select(-Regimen) %>% -->
<!--   kable(digits = 2, -->
<!--         caption = "Decision percentages when tau_MAV = tau_TV = 0.05") %>% -->
<!--   kable_styling() %>% -->
<!--   group_rows("Slope, %: -10%", start_row = 1, end_row = 5) %>% -->
<!--   group_rows("Slope, %: 10%", start_row = 6, end_row = 10) %>% -->
<!--   group_rows("Slope, %: 20%", start_row = 11, end_row = 15) %>% -->
<!--   group_rows("Slope, %: 30%", start_row = 16, end_row = 20) %>% -->
<!--   group_rows("Slope, %: 40%", start_row = 21, end_row = 25) -->
<!-- ``` -->

```{r}
load(here("data","cleaned","2022-06-22_mcmc_random-intercept-random-slope_nk-30_even.RData"))
```

```{r area-plot_different-tv-mav-risk, eval = FALSE, cache = TRUE}
# 1 Winner
tau_tv <- list(0.025, 0.025, 0.025, 0.025, 0.025)
names(tau_tv) <- tau_tv
tau_mav <- list(0.025, 0.05, 0.1, 0.15, 0.2)
names(tau_mav) <- tau_mav

d30 <- NULL
for (i in 1:length(tau_mav)){
  out <- map_dfr(list(mcmc_mods_even_30),
                 ~decision_function(mcmc_list = .x,
                                    nk = 30,
                                    theta_mav = 0,
                                    theta_tv = 20,
                                    tau_mav = tau_mav[[i]],
                                    tau_tv = tau_tv[[i]]))
  out <- out %>% mutate(tau_mav = tau_mav[[i]])
  d30 <- bind_rows(d30, out)
}


d30 %>% 
  group_by(tau_mav, Regimen, Decision) %>% 
  summarise(n = n()) %>% 
  group_by(tau_mav, Regimen) %>% 
  summarise(prop = n/sum(n),
            Decision = factor(Decision, levels = c("NO-GO", "Continue", "GO"))) %>% 
  mutate(Regimen = case_when(Regimen == "Regimen 1" ~ "10%",
                             Regimen == "Regimen 2" ~ "20%",
                             Regimen == "Regimen 3" ~ "30%",
                             Regimen == "Regimen 4" ~ "40%")) %>% 
  ggplot(aes(x = tau_mav, y = prop, fill = Decision)) + 
  facet_wrap(~Regimen) +
  # geom_bar(stat="identity") + 
  geom_area() +
  scale_fill_manual(values = c("red", ucsf_col_pal[8], ucsf_col_pal[4]),
                    breaks = c("NO-GO", "Continue", "GO"),
                    labels = c("NO-GO", "Continue", "GO")) +
  ggpubr::theme_pubr() + 
  xlab(TeX("$\\tau_{mav}")) +
  scale_y_continuous("Decision Probability",
                     breaks = seq(0,1,by = 0.1),
                     labels = seq(0,1,by = 0.1)) +
  theme(legend.position = "bottom")


tau_mav <- list(0.025, 0.025, 0.025, 0.025, 0.025)
names(tau_mav) <- tau_mav
tau_tv <- list(0.025, 0.05, 0.1, 0.15, 0.2)
names(tau_tv) <- tau_tv

d30_tv <- NULL
for (i in 1:length(tau_mav)){
  out <- map_dfr(list(mcmc_mods_even_30),
                 ~decision_function(mcmc_list = .x,
                                    nk = 30,
                                    theta_mav = 0,
                                    theta_tv = 20,
                                    tau_mav = tau_mav[[i]],
                                    tau_tv = tau_tv[[i]]))
  out <- out %>% mutate(tau_tv = tau_tv[[i]])
  d30_tv <- bind_rows(d30_tv, out)
}

d30_tv %>% 
  group_by(tau_tv, Regimen, Decision) %>% 
  summarise(n = n()) %>% 
  group_by(tau_tv, Regimen) %>% 
  summarise(prop = n/sum(n),
            Decision = factor(Decision, levels = c("NO-GO", "Continue", "GO"))) %>% 
  mutate(Regimen = case_when(Regimen == "Regimen 1" ~ "-10%",
                             Regimen == "Regimen 2" ~ "10%",
                             Regimen == "Regimen 3" ~ "35%",
                             Regimen == "Regimen 4" ~ "40%")) %>% 
  ggplot(aes(x = tau_tv, y = prop, fill = Decision)) + 
  facet_wrap(~Regimen) +
  # geom_bar(stat="identity") + 
  geom_area() +
  scale_fill_manual(values = c("red", ucsf_col_pal[8], ucsf_col_pal[4]),
                    breaks = c("NO-GO", "Continue", "GO"),
                    labels = c("NO-GO", "Continue", "GO")) +
  ggpubr::theme_pubr() + 
  xlab(TeX("$\\tau_{TV}")) +
  scale_y_continuous("Decision Probability",
                     breaks = seq(0,1,by = 0.1),
                     labels = seq(0,1,by = 0.1)) +
  theme(legend.position = "bottom")
```

### Ranking 

```{r }
load(here("data", "analyzed", "ranking", "2022-07-07_ranking-probabilities.RData"))
load(here("data", "analyzed", "ranking", "2022-07-07_compare-v-control.RData"))
```

#### $\psi_1$: Comparing Against Control

```{r }

p30 <- comparisons %>%
  filter(nk == "nk30") %>%
  mutate(condition = factor(condition, levels = c("1 Winner", "2 Winners", "4 Winners"))) %>% 
  pivot_longer(cols = p.regimen.2.v.control:p.regimen.5.v.control,
               names_to = "comparison",
               values_to = "posterior") %>% 
  mutate(comparison = case_when(comparison == "p.regimen.5.v.control" ~ "$\\theta_{5}$",
                                comparison == "p.regimen.4.v.control" ~ "$\\theta_{4}$",
                                comparison == "p.regimen.3.v.control" ~ "$\\theta_{3}$",
                                comparison == "p.regimen.2.v.control" ~ "$\\theta_{2}$")) %>% 
  ggplot(aes(y = comparison, x = posterior)) + 
  facet_wrap(~condition, ncol = 1) + 
  geom_point(position = position_jitter(width = 0, height = 0.35),
             aes(col = comparison),
             alpha = 0.5) +
  geom_boxplot(alpha = 0.3, # NEED TO INCORPORATE SAMPLE SIZE!!!
               width = 0.3,
               outlier.shape = NA,
               col = "white") +
  scale_color_manual(values = ucsf_col_pal) +
  scale_y_discrete(labels = TeX) +
  scale_x_continuous(TeX("$Pr_{\\theta}(\\theta > \\theta_1 | X)$"),
                     breaks = seq(0,1,by = 0.2),
                     labels = seq(0,1,by = 0.2)) +
  ggpubr::theme_pubr() +
  theme(legend.position = "none",
        axis.title.y = element_blank())

p40 <- comparisons %>%
  filter(nk == "nk40") %>%
  mutate(condition = factor(condition, levels = c("1 Winner", "2 Winners", "4 Winners"))) %>% 
  pivot_longer(cols = p.regimen.2.v.control:p.regimen.5.v.control,
               names_to = "comparison",
               values_to = "posterior") %>% 
  mutate(comparison = case_when(comparison == "p.regimen.5.v.control" ~ "$\\theta_{5}$",
                                comparison == "p.regimen.4.v.control" ~ "$\\theta_{4}$",
                                comparison == "p.regimen.3.v.control" ~ "$\\theta_{3}$",
                                comparison == "p.regimen.2.v.control" ~ "$\\theta_{2}$")) %>% 
  ggplot(aes(y = comparison, x = posterior)) + 
  facet_wrap(~condition, ncol = 1) + 
  geom_point(position = position_jitter(width = 0, height = 0.35),
             aes(col = comparison),
             alpha = 0.5) +
  geom_boxplot(alpha = 0.3, # NEED TO INCORPORATE SAMPLE SIZE!!!
               width = 0.3,
               outlier.shape = NA,
               col = "white") +
  scale_color_manual(values = ucsf_col_pal) +
  scale_y_discrete(labels = TeX) +
  scale_x_continuous(TeX("$Pr_{\\theta}(\\theta > \\theta_1 | X)$"),
                     breaks = seq(0,1,by = 0.2),
                     labels = seq(0,1,by = 0.2)) +
  ggpubr::theme_pubr() +
  theme(legend.position = "none",
        axis.title.y = element_blank())

p60 <- comparisons %>%
  filter(nk == "nk60") %>%
  mutate(condition = factor(condition, levels = c("1 Winner", "2 Winners", "4 Winners"))) %>% 
  pivot_longer(cols = p.regimen.2.v.control:p.regimen.5.v.control,
               names_to = "comparison",
               values_to = "posterior") %>% 
  mutate(comparison = case_when(comparison == "p.regimen.5.v.control" ~ "$\\theta_{5}$",
                                comparison == "p.regimen.4.v.control" ~ "$\\theta_{4}$",
                                comparison == "p.regimen.3.v.control" ~ "$\\theta_{3}$",
                                comparison == "p.regimen.2.v.control" ~ "$\\theta_{2}$")) %>% 
  ggplot(aes(y = comparison, x = posterior)) + 
  facet_wrap(~condition, ncol = 1) + 
  geom_point(position = position_jitter(width = 0, height = 0.35),
             aes(col = comparison),
             alpha = 0.5) +
  geom_boxplot(alpha = 0.3, # NEED TO INCORPORATE SAMPLE SIZE!!!
               width = 0.3,
               outlier.shape = NA,
               col = "white") +
  scale_color_manual(values = ucsf_col_pal) +
  scale_y_discrete(labels = TeX) +
  scale_x_continuous(TeX("$Pr_{\\theta}(\\theta > \\theta_1 | X)$"),
                     breaks = seq(0,1,by = 0.2),
                     labels = seq(0,1,by = 0.2)) +
  ggpubr::theme_pubr() +
  theme(legend.position = "none",
        axis.title.y = element_blank())

p30 + p40 + p60 + 
  plot_annotation(tag_levels = "A") 
```

```{r eval = FALSE}
ggsave(filename = here("graphs", "simulation-results", "random-intercept-random-slope",
                       paste0(Sys.Date(), "_point-boxplot-posterior-comparison-v-control.png")),
       device = "png",
       height = 6,
       width = 10,
       units = "in")
```

```{r barplot-posterior-prob-top1, eval = FALSE}
even_stat <- ranking_probabilities$even_probabilities %>% 
  group_by(sim, nk) %>% 
  mutate(top = as.numeric(p.subset.1 == max(p.subset.1))) %>% 
  group_by(regimen, nk) %>% 
  summarise(n_top = sum(top)) %>% 
  mutate(condition = "1 Winner")
hl_stat <- ranking_probabilities$highlow_probabilities %>% 
  group_by(sim, nk) %>% 
  mutate(top = as.numeric(p.subset.1 == max(p.subset.1))) %>% 
  group_by(regimen, nk) %>% 
  summarise(n_top = sum(top)) %>% 
  mutate(condition = "2 Winners")
high_stat <- ranking_probabilities$high_probabilities %>% 
  group_by(sim, nk) %>% 
  mutate(top = as.numeric(p.subset.1 == max(p.subset.1))) %>% 
  group_by(regimen, nk) %>% 
  summarise(n_top = sum(top)) %>% 
  mutate(condition = "4 Winners")

bind_rows(even_stat,
          hl_stat,
          high_stat) %>% 
  mutate(theta = paste0("$\\theta_{(", 6 - as.numeric(str_remove(regimen, "arm")), ")}$"),
         condition = factor(condition, levels = c("1 Winner", "2 Winners", "4 Winners"))) %>%
  mutate(theta = factor(theta, levels = paste0("$\\theta_{(", 5:1, ")}$"))) %>% 
  ggplot(aes(x = nk, y = n_top, fill = theta)) + 
  facet_wrap(~condition, nrow = 1) +
  geom_area(position = "stack",
            alpha = 0.9) +
  scale_fill_manual(values = ucsf_col_pal[1:5], 
                    labels = TeX) +
  coord_cartesian(ylim = c(0,1000)) +
  scale_y_continuous(TeX("$p_3$"),
                     breaks = seq(0,1000,by = 200),
                     labels = seq(0,1,by = 0.2)) +
  scale_x_continuous(TeX("$n_k$")) +
  ggpubr::theme_pubr() +
  theme(legend.position = c(0.9,0.22),
        legend.title = element_blank(),
        legend.margin = margin(0,2,1,1),
        legend.direction = "vertical",
        axis.title.y = element_blank())

  # ggplot(aes(x = nk, y = n_top, fill = regimen)) + 
  # geom_bar(stat = "identity") +
  # scale_fill_manual("")
```

```{r}
p1 <- mutate(ranking_probabilities$even_probabilities, condition = "1 Winner") %>% 
  filter(regimen %in% c("arm4", "arm5"),
         nk < 60) %>% 
  mutate(theta = paste0("$\\theta_{(", 6 - as.numeric(str_remove(regimen, "arm")), ")}$")) %>% 
  mutate(theta = factor(theta, levels = paste0("$\\theta_{(", 5:1, ")}$"))) %>% 
  group_by(regimen, nk) %>% 
  mutate(median = median(p.subset.1)) %>% 
  ggplot(aes(x = p.subset.1, fill = theta)) + 
  geom_density(alpha = 0.6,
               col = "white") + 
  geom_segment(aes(x = median, xend = median, y = 0, yend = 2.5, col = theta, lty = regimen)) +
  geom_point(aes(x = median, y = 0.1, bg = theta),
             shape = 24,
             size = 2,
             col = "white") +
  scale_fill_manual(values = ucsf_col_pal[1:5], 
                    labels = TeX) +
  scale_color_manual(values = ucsf_col_pal[1:5], 
                     labels = TeX) +
  scale_linetype_manual(values = c(2,3), 
                        labels = TeX,
                        guide = "none") +
  facet_wrap(~nk, ncol = 1) + 
  coord_cartesian(ylim = c(0,2.75)) +
  scale_x_continuous(TeX("$\\Pr_{\\theta}(\\theta_k = \\theta_{(1)}|X)$")) +
  ggpubr::theme_pubr() +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        legend.position = "none",
        legend.title = element_blank(),
        legend.margin = margin(0,2,1,1),
        legend.direction = "vertical",
        axis.title.y = element_blank())

p2 <- mutate(ranking_probabilities$highlow_probabilities, condition = "2 Winners") %>% 
  filter(regimen %in% c("arm4", "arm5"),
         nk < 60) %>% 
  mutate(theta = paste0("$\\theta_{(", 6 - as.numeric(str_remove(regimen, "arm")), ")}$")) %>% 
  mutate(theta = factor(theta, levels = paste0("$\\theta_{(", 5:1, ")}$"))) %>% 
  group_by(regimen, nk) %>% 
  mutate(median = median(p.subset.1)) %>% 
  ggplot(aes(x = p.subset.1, fill = theta)) + 
  geom_density(alpha = 0.6,
               col = "white") + 
  geom_segment(aes(x = median, xend = median, y = 0, yend = 2.5, col = theta, lty = theta)) +
  geom_point(aes(x = median, y = 0.1, bg = theta),
             shape = 24,
             size = 2,
             col = "white") +
  coord_cartesian(ylim = c(0,2.75)) +
  scale_fill_manual(values = ucsf_col_pal[1:5], 
                    labels = TeX) +
  scale_color_manual(values = ucsf_col_pal[1:5], 
                    labels = TeX) +
  scale_linetype_manual(values = c(2,3), 
                        labels = TeX,
                        guide = "none") +
  facet_wrap(~nk, ncol = 1) + 
  scale_x_continuous(TeX("$\\Pr_{\\theta}(\\theta_k = \\theta_{(1)}|X)$")) +
  ggpubr::theme_pubr() +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        legend.position = "none",
        legend.title = element_blank(),
        legend.margin = margin(0,2,1,1),
        legend.direction = "vertical",
        axis.title.y = element_blank())

p3 <- mutate(ranking_probabilities$high_probabilities, condition = "4 Winners") %>% 
  filter(regimen %in% c("arm4", "arm5"),
         nk < 60) %>% 
  mutate(theta = paste0("$\\theta_{(", 6 - as.numeric(str_remove(regimen, "arm")), ")}$")) %>% 
  mutate(theta = factor(theta, levels = paste0("$\\theta_{(", 5:1, ")}$"))) %>% 
  group_by(regimen, nk) %>% 
  mutate(median = median(p.subset.1)) %>% 
  ggplot(aes(x = p.subset.1, fill = theta)) + 
  geom_density(alpha = 0.6,
               col = "white") + 
  geom_segment(aes(x = median, xend = median, y = 0, yend = 2.5, col = theta, lty = theta)) +
  geom_point(aes(x = median, y = 0.1, bg = theta),
             shape = 24,
             col = "white") +
  scale_fill_manual(values = ucsf_col_pal[1:2],
                    labels = TeX) +
  scale_color_manual(values = ucsf_col_pal[1:5], 
                     labels = TeX,
                     # aesthetics = c("color", "bg", "fill")) +#,
                     guide = "none") +
  scale_linetype_manual(values = c(2,3), 
                        labels = TeX,
                        guide = "none") +
  coord_cartesian(ylim = c(0,2.75)) +
  facet_wrap(~nk, ncol = 1) + 
  scale_x_continuous(TeX("$\\Pr_{\\theta}(\\theta_k = \\theta_{(1)}|X)$")) +
  ggpubr::theme_pubr() +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        legend.position = c(0.9,0.15),
        legend.title = element_blank(),
        legend.margin = margin(0,2,1,1),
        legend.direction = "vertical",
        axis.title.y = element_blank())

p1 + p2 + p3 + 
  plot_annotation(tag_levels = "A") 
```

```{r eval = FALSE}
ggsave(filename = here("graphs", "simulation-results", "random-intercept-random-slope", 
                       paste0(Sys.Date(), "_density-plot_prob-steepest_top-2.png")),
       device = "png",
       width = 10,
       height = 5,
       units = "in")

ggsave(filename = here("graphs", "submission", "fig-05_density-plot_prob-steepest_top-2.tiff"),
       device = "tiff",
       width = 10,
       height = 5,
       units = "in")

p1 + p2 + p3 + 
  plot_annotation(tag_levels = "A",
                  title = "Dufault Fig. 5 (Top)") 

ggsave(filename = here("graphs", "submission", "fig-05_density-plot_prob-steepest_top-2_annotated.tiff"),
       device = "tiff",
       dpi = 600,
       width = 10,
       height = 5,
       units = "in")
```

#### $f(\psi_2)$: Comparing estimated confidence in top 2 regimens 

```{r boxplot-posterior-prob-top1}
ranking_probabilities$even_probabilities %>% 
  filter(regimen != "arm1") %>% 
  mutate(regimen.perc = case_when(regimen == "arm2" ~ "10%",
                                  regimen == "arm3" ~ "20%",
                                  regimen == "arm4" ~ "30%",
                                  regimen == "arm5" ~ "40%"),
         nk = as.factor(nk)) %>% 
  ggplot(aes(x = nk, y = p.subset.1)) +
  facet_wrap(~regimen.perc) +
  geom_violin(col = ucsf_col_pal[1],
              fill = ucsf_col_pal[1],
              width = 1,
              alpha = 0.3) +
  geom_boxplot(width = 0.1,
               outlier.shape = NA,
               fill = "white") +
  ylab(TeX("Pr$_{\\theta}(\\theta_{k} = \\theta_{(1)}$)")) + 
  xlab(TeX("Sample size per regimen, $n_k$")) + 
  ggpubr::theme_pubr()

p1 <- ranking_probabilities$even_probabilities %>% 
  ggplot(aes(x = p.subset.1, y = regimen, col = regimen, fill = regimen)) +
  facet_wrap(~nk, nrow = 1) +
  geom_boxplot(width = 0.6,
               alpha = 0.5) +
  scale_x_continuous(TeX("$\\Pr_{\\theta}(\\theta_k = \\theta_{(1)})$"),
                     breaks = seq(0,1,by = 0.2),
                     labels = seq(0,1,by = 0.2)) +
  scale_y_discrete("Slope, %", 
                   labels = c("Control", "10%", "20%", "30%", "40%")) +
  scale_color_manual(values = ucsf_col_pal) +
  scale_fill_manual(values = ucsf_col_pal) +
  ggpubr::theme_pubr() + 
  theme(legend.position = "none")  

p2 <- ranking_probabilities$highlow_probabilities %>% 
  ggplot(aes(x = p.subset.1, y = regimen, col = regimen, fill = regimen)) +
  facet_wrap(~nk, nrow = 1) +
  geom_boxplot(width = 0.6,
               alpha = 0.5) +
  scale_x_continuous(TeX("$\\Pr_{\\theta}(\\theta_k = \\theta_{(1)})$"),
                     breaks = seq(0,1,by = 0.2),
                     labels = seq(0,1,by = 0.2)) +
  scale_y_discrete("Slope, %", 
                   labels = c("Control", "-10%", "10%", "35%", "40%")) +
  scale_color_manual(values = ucsf_col_pal) +
  scale_fill_manual(values = ucsf_col_pal) +
  ggpubr::theme_pubr() + 
  theme(legend.position = "none")  

p3 <- ranking_probabilities$high_probabilities %>% 
  ggplot(aes(x = p.subset.1, y = regimen, col = regimen, fill = regimen)) +
  facet_wrap(~nk, nrow = 1) +
  geom_boxplot(width = 0.6,
               alpha = 0.5) +
  scale_x_continuous(TeX("$\\Pr_{\\theta}(\\theta_k = \\theta_{(1)})$"),
                     breaks = seq(0,1,by = 0.2),
                     labels = seq(0,1,by = 0.2)) +
  scale_y_discrete("Slope, %", 
                   labels = c("Control", "35%", "37%", "39%", "41%")) +
  scale_color_manual(values = ucsf_col_pal) +
  scale_fill_manual(values = ucsf_col_pal) +
  ggpubr::theme_pubr() + 
  theme(legend.position = "none")  

p1 / p2 / p3 +
  plot_annotation(tag_levels = "A") 
```

```{r eval = FALSE}
ggsave(filename = here("graphs", "simulation-results", "random-intercept-random-slope", 
                       paste0(Sys.Date(), "_boxplot-posterior-prob-top1.png")),
       device = "png",
       height = 6,
       width = 10,
       units = "in")
```

```{r}
p1 <- ranking_probabilities$even_probabilities %>% 
  filter(regimen %in% c("arm4", "arm5")) %>%  # Take the two true best arms
  dplyr::select(sim, regimen, p.subset.1, nk) %>% 
  pivot_wider(values_from = p.subset.1,
              names_from = regimen) %>% 
  mutate(p.diff = arm5 - arm4) %>% 
  ggplot(aes(x = as.factor(nk), y = p.diff)) + 
  geom_point(position = position_jitter(height = 0, width = 0.45),
             alpha = 0.1,
             aes(col = p.diff > 0)) + 
  scale_color_manual(values = ucsf_col_pal[3:4]) +
  geom_hline(yintercept = 0, 
             col= ucsf_col_pal[3],
             size = 1) + 
  geom_violin(width = 1,
              alpha = 0.6) +
  geom_boxplot(width = 0.05,
               outlier.shape = NA,
               fill = "darkgray",
               alpha = 0.5) +
  ggpubr::theme_pubr() +
  coord_cartesian(xlim = c(0,5)) + 
  ylab(TeX("$\\widehat{\\psi}_{2,(1)} - \\widehat{\\psi}_{2,(2)}$")) + 
  xlab(TeX("Sample size per regimen, $n_k$")) + 
  annotate(geom = "text",
           x = -0.35, y = 0,
           col = ucsf_col_pal[4],
           hjust = 0,
           vjust = -0.5,
           label = "Favors true\nbest regimen") +
  annotate(geom = "text",
           x = -0.35, y = 0,
           col = ucsf_col_pal[3],
           hjust = 0,
           vjust = 1.5,
           label = "Favors second\nbest regimen") + 
  theme(legend.position = "none",
        axis.title.x = element_blank())

p2 <- ranking_probabilities$highlow_probabilities %>% 
  filter(regimen %in% c("arm4", "arm5")) %>%  # Take the two true best arms
  dplyr::select(sim, regimen, p.subset.1, nk) %>% 
  pivot_wider(values_from = p.subset.1,
              names_from = regimen) %>% 
  mutate(p.diff = arm5 - arm4) %>% 
  ggplot(aes(x = as.factor(nk), y = p.diff)) + 
  geom_point(position = position_jitter(height = 0, width = 0.45),
             alpha = 0.1,
             aes(col = p.diff > 0)) + 
  scale_color_manual(values = ucsf_col_pal[3:4]) +
  geom_hline(yintercept = 0, 
             col= ucsf_col_pal[3],
             size = 1) + 
  geom_violin(width = 1,
              alpha = 0.6) +
  geom_boxplot(width = 0.05,
               outlier.shape = NA,
               fill = "darkgray",
               alpha = 0.5) +
  ggpubr::theme_pubr() +
  coord_cartesian(xlim = c(0,5)) + 
  ylab(TeX("$\\widehat{\\psi}_{2,(1)} - \\widehat{\\psi}_{2,(2)}$")) + 
  xlab(TeX("Sample size per regimen, $n_k$")) + 
  annotate(geom = "text",
           x = -0.35, y = 0,
           col = ucsf_col_pal[4],
           hjust = 0,
           vjust = -0.5,
           label = "Favors true\nbest regimen") +
  annotate(geom = "text",
           x = -0.35, y = 0,
           col = ucsf_col_pal[3],
           hjust = 0,
           vjust = 1.5,
           label = "Favors second\nbest regimen") + 
  theme(legend.position = "none")
  
p3 <- ranking_probabilities$high_probabilities %>% 
  filter(regimen %in% c("arm4", "arm5")) %>%  # Take the two true best arms
  dplyr::select(sim, regimen, p.subset.1, nk) %>% 
  pivot_wider(values_from = p.subset.1,
              names_from = regimen) %>% 
  mutate(p.diff = arm5 - arm4) %>% 
  ggplot(aes(x = as.factor(nk), y = p.diff)) + 
  geom_point(position = position_jitter(height = 0, width = 0.45),
             alpha = 0.1,
             aes(col = p.diff > 0)) + 
  scale_color_manual(values = ucsf_col_pal[3:4]) +
  geom_hline(yintercept = 0, 
             col= ucsf_col_pal[3],
             size = 1) + 
  geom_violin(width = 1,
              alpha = 0.6) +
  geom_boxplot(width = 0.05,
               outlier.shape = NA,
               fill = "darkgray",
               alpha = 0.5) +
  ggpubr::theme_pubr() +
  coord_cartesian(xlim = c(0,5)) + 
  ylab(TeX("$\\widehat{\\psi}_{2,(1)} - \\widehat{\\psi}_{2,(2)}$")) + 
  xlab(TeX("Sample size per regimen, $n_k$")) + 
  annotate(geom = "text",
           x = -0.35, y = 0,
           col = ucsf_col_pal[4],
           hjust = 0,
           vjust = -0.5,
           label = "Favors true\nbest regimen") +
  annotate(geom = "text",
           x = -0.35, y = 0,
           col = ucsf_col_pal[3],
           hjust = 0,
           vjust = 1.5,
           label = "Favors second\nbest regimen") + 
  theme(legend.position = "none",
        axis.title.x = element_blank())


ggpubr::ggarrange(p1, p2, p3, ncol = 1,
                  labels = "AUTO")
```

```{r eval = FALSE}
ggsave(filename = here("graphs", "simulation-results", "random-intercept-random-slope",
                       paste0(Sys.Date(), "_violin-box-point_posterior-comparison_best-v-second-best.png")),
       height = 10,
       width = 8,
       units = "in",
       device = "png"
)
```

#### $\psi_3$: Posterior probability of ranking in top 2 

```{r}
p1 <- ranking_probabilities$even_probabilities %>% 
  ggplot(aes(x = regimen, y = p.subset.2, col = regimen)) + 
  facet_wrap(~as.factor(nk), nrow = 1) + 
  geom_boxplot(aes(fill = regimen),
               alpha = 0.5,
               width = 0.6) + 
  scale_x_discrete("Slope, %",
                   labels = c("Control", "10%", "20%", "30%", "40%")) +
  scale_color_manual(values = ucsf_col_pal) +
  scale_fill_manual(values = ucsf_col_pal) +
  scale_y_continuous(TeX("P$(\\theta \\in \\{\\theta_{(1)}, \\theta_{(2)}\\})$"),
                     breaks = seq(0,1,by = 0.2),
                     labels = seq(0,1,by = 0.2)) + 
  ggpubr::theme_pubr() +
  theme(legend.position = "none",
        axis.text.x = element_blank(),
        axis.title.x = element_blank()) + 
  coord_flip()

p2 <- ranking_probabilities$highlow_probabilities %>% 
  ggplot(aes(x = regimen, y = p.subset.2, col = regimen)) + 
  facet_wrap(~as.factor(nk), nrow = 1) + 
  geom_boxplot(aes(fill = regimen),
               alpha = 0.5,
               width = 0.6) + 
  scale_x_discrete("Slope, %",
                   labels = c("Control", "-10%", "10%", "35%", "40%")) +
  scale_color_manual(values = ucsf_col_pal) +
  scale_fill_manual(values = ucsf_col_pal) +
  scale_y_continuous(TeX("P$(\\theta \\in \\{\\theta_{(1)}, \\theta_{(2)}\\})$"),
                     breaks = seq(0,1,by = 0.2),
                     labels = seq(0,1,by = 0.2)) + 
  ggpubr::theme_pubr() +
  theme(legend.position = "none",
        axis.text.x = element_blank(),
        axis.title.x = element_blank()) + 
  coord_flip()

p3 <- ranking_probabilities$high_probabilities %>% 
  ggplot(aes(x = regimen, y = p.subset.2, col = regimen)) + 
  facet_wrap(~as.factor(nk), nrow = 1) + 
  geom_boxplot(aes(fill = regimen),
               alpha = 0.5,
               width = 0.6) + 
  scale_x_discrete("Slope, %",
                   labels = c("Control", "35%", "37%", "39%", "41%")) +
  scale_color_manual(values = ucsf_col_pal) +
  scale_fill_manual(values = ucsf_col_pal) +
  scale_y_continuous(TeX("$\\psi_3 = Pr_{\\theta}(\\theta \\in \\{\\theta_{(1)}, \\theta_{(2)}\\}|X)$"),
                     breaks = seq(0,1,by = 0.2),
                     labels = seq(0,1,by = 0.2)) + 
  ggpubr::theme_pubr() +
  theme(legend.position = "none") +
  coord_flip()

p1 / p2 / p3 +
  plot_annotation(tag_levels = "A") 
```

```{r eval = FALSE}
ggsave(filename = here("graphs", "simulation-results", "random-intercept-random-slope", 
                       paste0(Sys.Date(), "_boxplot-posterior-prob-top2.png")),
       device = "png",
       height = 6,
       width = 10,
       units = "in")
```

```{r}
temp1 <- ranking_probabilities$even_probabilities %>% 
  group_by(sim, nk) %>% 
  summarise(n.greater.than = min(p.subset.2[regimen %in% c("arm5", "arm4")]) > max(p.subset.2[!regimen %in% c("arm5", "arm4")])) %>% 
  group_by(nk) %>% 
  summarise(p.greater.than = mean(n.greater.than)) %>%
  mutate(condition = "1 Winner")

temp2 <- ranking_probabilities$high_probabilities %>% 
  group_by(sim, nk) %>% 
  summarise(n.greater.than = min(p.subset.2[regimen %in% c("arm5", "arm4")]) > max(p.subset.2[!regimen %in% c("arm5", "arm4")])) %>% 
  group_by(nk) %>% 
  summarise(p.greater.than = mean(n.greater.than)) %>%
  mutate(condition = "4 Winners")

temp3 <- ranking_probabilities$highlow_probabilities %>% 
  group_by(sim, nk) %>% 
  summarise(n.greater.than = min(p.subset.2[regimen %in% c("arm5", "arm4")]) > max(p.subset.2[!regimen %in% c("arm5", "arm4")])) %>% 
  group_by(nk) %>% 
  summarise(p.greater.than = mean(n.greater.than)) %>%
  mutate(condition = "2 Winners")

p1 <- bind_rows(temp1, temp2, temp3) %>% 
  ggplot(aes(x = nk, y = p.greater.than, col = condition, lty = condition)) + 
  geom_line(size = 1) +
  scale_y_continuous(TeX("Pr($\\min\\{\\psi_{3,(1)},\\psi_{3,(2)}\\}$ > $\\max\\{\\psi_{3,(3)},\\psi_{3,(4)},\\psi_{3,(5)}\\})$"),
                     breaks = seq(0,1,by = 0.2),
                     labels = seq(0,1,by = 0.2)) +
  scale_color_manual(values = ucsf_col_pal) +
  scale_x_continuous(TeX("$n_k$"))+
  ggpubr::theme_pubr() +
  coord_cartesian(ylim = c(0,1)) + 
  theme(legend.title = element_blank(),
        legend.position = c(0.92,0.15))

p1
```

```{r eval = FALSE}
ggsave(filename = here("graphs", "simulation-results", "random-intercept-random-slope",
                       paste0(Sys.Date(), "_lineplot-psi3-vis.png")),
       device = "png",
       width = 5,
       height = 5,
       units = "in")
```

## Together

<!-- + TTP (high-low) and Mixed survival rates such that: -->
<!--   + Regimen 1 (control): 5% relapse rate, reference log10(TTP) slope -->
<!--   + Regimen 2 (sub-optimal regimen): 10% relapse rate, -10% relative log10(TTP) slope -->
<!--   + Regimen 3 (minimal regimen): 5% relapse rate, 10% relative log10(TTP) slope -->
<!--   + Regimen 4 (minimal regimen): 5% relapse rate, 35% relative log10(TTP) slope -->
<!--   + Regimen 5 (desirable regimen): 2.5% relapse rate, 40% relative log10(TTP) slope -->
  
<!-- ### Stopping sub-optimal regimens -->

<!-- Stopping based on:     -->

<!-- + TTP decision: NO-GO -->
<!-- + P(rank in top 2) < 60% -->
<!-- + Unfavorable Outcomes >= 2 -->

<!-- ```{r data-combined, eval = TRUE} -->
<!-- ###################### -->
<!-- # Regimen 2 (Sub-optimal) -->
<!-- ###################### -->
<!-- # relapses -->
<!-- out_hl_30_relapse_r1 <- s95.sit1.30 %>% # Situation 1: Regimen 2 - Sub-optimal -->
<!--   filter(ttp.condition == "highlow", regimen == "2") %>%  # TTP did not play a role in simulating relapse data. Selection of ttp condition is irrelevant to the relapses counted. However, a unique relapse dataset was generated for each ttp condition so we will take advantage of this by pulling out the sub-optimal relapse counts from each dataset. -->
<!--   dplyr::select(-regimen, -ttp.condition) -->
<!-- out_hl_30_relapse_r2 <- s95.sit1.30 %>% # Situation 1: Regimen 2 - Sub-optimal -->
<!--   filter(ttp.condition == "high", regimen == "2") %>%   -->
<!--   dplyr::select(-regimen, -ttp.condition) -->
<!-- out_hl_30_relapse_r3 <- s95.sit1.30 %>% # Situation 1: Regimen 2 - Sub-optimal -->
<!--   filter(ttp.condition == "even", regimen == "2") %>%  -->
<!--   dplyr::select(-regimen, -ttp.condition) -->

<!-- # TPP decision -->
<!-- out_hl_30_tpp_r1 <- decisions$decisions_highlow %>% # -10% slope -->
<!--   filter(Regimen == "Regimen 1", nk == 30) %>% # indexing sets control at 0 -->
<!--   dplyr::select(-Regimen) -->
<!-- out_hl_30_tpp_r2 <- decisions$decisions_highlow %>% # 10% slope -->
<!--   filter(Regimen == "Regimen 2", nk == 30) %>% # indexing sets control at 0 -->
<!--   dplyr::select(-Regimen) -->
<!-- out_hl_30_tpp_r3 <- decisions$decisions_even %>% # 20% slope -->
<!--   filter(Regimen == "Regimen 2", nk == 30) %>% # indexing sets control at 0 -->
<!--   dplyr::select(-Regimen) -->

<!-- # Ranking -->
<!-- out_hl_30_ranking_r1 <- map_dfr(filter(ranking_probabilities$highlow_probabilities, nk == 30), -->
<!--                              ~.x, .id = "sim") %>%  -->
<!--   filter(regimen == "arm2") %>% # -10% slope -->
<!--   dplyr::select(-regimen) -->
<!-- out_hl_30_ranking_r2 <- map_dfr(filter(ranking_probabilities$highlow_probabilities, nk == 30), -->
<!--                              ~.x, .id = "sim") %>%  -->
<!--   filter(regimen == "arm3") %>% # 10% slope -->
<!--   dplyr::select(-regimen) -->
<!-- out_hl_30_ranking_r3 <- map_dfr(filter(ranking_probabilities$even_probabilities, nk == 30), -->
<!--                              ~.x, .id = "sim") %>%  -->
<!--   filter(regimen == "arm3") %>% #20% slope -->
<!--   dplyr::select(-regimen) -->

<!-- out_hl_30_r1 <- full_join( -->
<!--   full_join(out_hl_30_relapse_r1, out_hl_30_tpp_r1),  -->
<!--                        out_hl_30_ranking_r1) -->
<!-- out_hl_30_r2 <- full_join( -->
<!--   full_join(out_hl_30_relapse_r2, out_hl_30_tpp_r2),  -->
<!--                        out_hl_30_ranking_r2) -->
<!-- out_hl_30_r3 <- full_join( -->
<!--   full_join(out_hl_30_relapse_r3, out_hl_30_tpp_r3),  -->
<!--                        out_hl_30_ranking_r3) -->
<!-- # Table(?)/Heatmap(?) -->
<!-- # focus in on sub-optimal regimens (relapse) -->
<!-- # sample size: 30 -->
<!-- # panels: A) -10%, B) 10%, C) 20% slope -->
<!-- # prop stopped relapse, prop stopped TPP, prop not ranked first or second, prop stopped relapse | prop stopped TPP, prop stopped relapse | prop stopped TPP | not ranked first or second -->

<!-- t1 <- out_hl_30_r1 %>%  -->
<!--   summarise(`Stop relapse` = mean(n_relapse_interim1 >= 2), -->
<!--             `Stop TPP` = mean(Decision == "NO-GO"), -->
<!--             `P(top 2) < 0.6` = mean(p.subset.2 < 0.6), -->
<!--             `Stop relapse or TPP` = mean((n_relapse_interim1 >= 2) | (Decision == "NO-GO")), -->
<!--             `Stop relapse or TPP or P(top 2) < 0.6` = mean((n_relapse_interim1 >= 2) | (Decision == "NO-GO") | mean(p.subset.2 < 0.6))) %>%  -->
<!--   mutate(Slope = "-10%", .before = 1) -->

<!-- t2 <- out_hl_30_r2 %>%  -->
<!--   summarise(`Stop relapse` = mean(n_relapse_interim1 >= 2), -->
<!--             `Stop TPP` = mean(Decision == "NO-GO"), -->
<!--             `P(top 2) < 0.6` = mean(p.subset.2 < 0.6), -->
<!--             `Stop relapse or TPP` = mean((n_relapse_interim1 >= 2) | (Decision == "NO-GO")), -->
<!--             `Stop relapse or TPP or P(top 2) < 0.6` = mean((n_relapse_interim1 >= 2) | (Decision == "NO-GO") | mean(p.subset.2 < 0.6))) %>%  -->
<!--   mutate(Slope = "10%", .before = 1) -->

<!-- t3 <- out_hl_30_r3 %>%  -->
<!--   summarise(`Stop relapse` = mean(n_relapse_interim1 >= 2), -->
<!--             `Stop TPP` = mean(Decision == "NO-GO"), -->
<!--             `P(top 2) < 0.6` = mean(p.subset.2 < 0.6), -->
<!--             `Stop relapse or TPP` = mean((n_relapse_interim1 >= 2) | (Decision == "NO-GO")), -->
<!--             `Stop relapse or TPP or P(top 2) < 0.6` = mean((n_relapse_interim1 >= 2) | (Decision == "NO-GO") | mean(p.subset.2 < 0.6))) %>%  -->
<!--   mutate(Slope = "20%", .before = 1) -->

<!-- bind_rows(t1, t2, t3) %>%  -->
<!--   kable(digits = 3) %>%  -->
<!--   kable_styling() -->

<!-- p_df <- data.frame(relapse = ifelse(out_hl_30_r1$n_relapse_interim1 >= 2, "NO-GO", "Other"), -->
<!--                    TPP = ifelse(out_hl_30_r1$Decision == "NO-GO", "NO-GO", "Other"), -->
<!--                    ranking = ifelse(out_hl_30_r1$p.subset.2 <= 0.6, "NO-GO", "Other")) %>%  -->
<!--   summarise(agree.relapse.rank = mean((relapse == ranking) & (relapse == "NO-GO") & (TPP == "Other")), -->
<!--             agree.relapse.TPP = mean((relapse == TPP) & (relapse == "NO-GO") & (ranking == "Other")), -->
<!--             agree.TPP.rank = mean((TPP == ranking) & (ranking == "NO-GO") & (relapse == "Other")), -->
<!--             agree.all = mean((TPP == ranking) & (TPP == relapse) & (relapse == "NO-GO")), -->
<!--             only.relapse = mean((relapse == "NO-GO") & (TPP == "Other") & (ranking == "Other")), -->
<!--             only.TPP = mean((TPP == "NO-GO") & (ranking == "Other") & (relapse == "Other")), -->
<!--             only.rank = mean((ranking == "NO-GO") & (TPP == "Other") & (relapse == "Other")), -->
<!--             p.missed = mean(relapse == "Other" & ranking == "Other" & TPP == "Other")) -->
<!-- p_df_2 <- data.frame(relapse = ifelse(out_hl_30_r2$n_relapse_interim1 >= 2, "NO-GO", "Other"), -->
<!--                  TPP = ifelse(out_hl_30_r2$Decision == "NO-GO", "NO-GO", "Other"), -->
<!--                  ranking = ifelse(out_hl_30_r2$p.subset.2 <= 0.6, "NO-GO", "Other")) %>%  -->
<!--   summarise(agree.relapse.rank = mean((relapse == ranking) & (relapse == "NO-GO") & (TPP == "Other")), -->
<!--             agree.relapse.TPP = mean((relapse == TPP) & (relapse == "NO-GO") & (ranking == "Other")), -->
<!--             agree.TPP.rank = mean((TPP == ranking) & (ranking == "NO-GO") & (relapse == "Other")), -->
<!--             agree.all = mean((TPP == ranking) & (TPP == relapse) & (relapse == "NO-GO")), -->
<!--             only.relapse = mean((relapse == "NO-GO") & (TPP == "Other") & (ranking == "Other")), -->
<!--             only.TPP = mean((TPP == "NO-GO") & (ranking == "Other") & (relapse == "Other")), -->
<!--             only.rank = mean((ranking == "NO-GO") & (TPP == "Other") & (relapse == "Other")), -->
<!--             p.missed = mean(relapse == "Other" & ranking == "Other" & TPP == "Other")) -->
<!-- p_df_3 <- data.frame(relapse = ifelse(out_hl_30_r3$n_relapse_interim1 >= 2, "NO-GO", "Other"), -->
<!--                  TPP = ifelse(out_hl_30_r3$Decision == "NO-GO", "NO-GO", "Other"), -->
<!--                  ranking = ifelse(out_hl_30_r3$p.subset.2 <= 0.6, "NO-GO", "Other")) %>%  -->
<!--   summarise(agree.relapse.rank = mean((relapse == ranking) & (relapse == "NO-GO") & (TPP == "Other")), -->
<!--             agree.relapse.TPP = mean((relapse == TPP) & (relapse == "NO-GO") & (ranking == "Other")), -->
<!--             agree.TPP.rank = mean((TPP == ranking) & (ranking == "NO-GO") & (relapse == "Other")), -->
<!--             agree.all = mean((TPP == ranking) & (TPP == relapse) & (relapse == "NO-GO")), -->
<!--             only.relapse = mean((relapse == "NO-GO") & (TPP == "Other") & (ranking == "Other")), -->
<!--             only.TPP = mean((TPP == "NO-GO") & (ranking == "Other") & (relapse == "Other")), -->
<!--             only.rank = mean((ranking == "NO-GO") & (TPP == "Other") & (relapse == "Other")), -->
<!--             p.missed = mean(relapse == "Other" & ranking == "Other" & TPP == "Other")) -->


<!-- p1 <- ggplot() +  -->
<!--   # TPP -->
<!--   geom_polygon(aes(x = 0+1*cos(seq(0,2*pi,length.out=100)),  -->
<!--                    y = 1+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[1], -->
<!--                alpha = 0.3) +  -->
<!--   # Ranking -->
<!--   geom_polygon(aes(x = -0.75+1*cos(seq(0,2*pi,length.out=100)), -->
<!--                    y = 2.25+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[2], -->
<!--                alpha = 0.3) +  -->
<!--   # Unfavorable Outcome -->
<!--   geom_polygon(aes(x = 0.75+1*cos(seq(0,2*pi,length.out=100)), -->
<!--                    y = 2.25+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[3], -->
<!--                alpha = 0.3) +  -->
<!--   annotate(geom = "text", x = 1.5, y = 3, hjust = 0, label = "Unfavorable Outcome", size = 5) +  -->
<!--   annotate(geom = "text", x = -1.5, y = 3, hjust = 1, label = "Ranking", size = 5) +  -->
<!--   annotate(geom = "text", x = 0, y = 0, vjust = 1.1, label = "TPP", size = 5) +  -->
<!--   coord_fixed(xlim = c(-3,3), -->
<!--               ylim = c(-0.5, 3.5)) + -->
<!--   annotate(geom = "text", x = 0.75, y = 2.25, label = round(100*p_df$only.relapse, 1), size = 5) + -->
<!--   annotate(geom = "text", x = -0.75, y = 2.25, label = round(100*p_df$only.rank, 1), size = 5) + -->
<!--   annotate(geom = "text", x = 0, y = 1, label = round(100*p_df$only.TPP, 1), size = 5) + -->
<!--   annotate(geom = "text", x = -0.375, y = 1.55, hjust = 1, label = round(100*p_df$agree.TPP.rank, 1)) + -->
<!--   annotate(geom = "text", x = 0.375, y = 1.55, hjust = 0, label = round(100*p_df$agree.relapse.TPP, 1)) + -->
<!--   annotate(geom = "text", x = 0, y = 1.85, label = round(100*p_df$agree.all, 1)) + -->
<!--   annotate(geom = "text", x = 0, y = 2.25, label = round(100*p_df$agree.relapse.rank, 1)) + -->
<!--   ggpubr::theme_pubr() +  -->
<!--   labs(caption = paste0("Sub-optimal regimens missed: ", round(p_df$p.missed*100, 2), "%")) + -->
<!--   theme(axis.line = element_blank(), -->
<!--         axis.text = element_blank(), -->
<!--         axis.title = element_blank(), -->
<!--         axis.ticks = element_blank(), -->
<!--         plot.title = element_text(hjust = 0.5)) +  -->
<!--   ggtitle("-10% Relative Slope, TTP") -->

<!-- p2 <- ggplot() +  -->
<!--   # TPP -->
<!--   geom_polygon(aes(x = 0+1*cos(seq(0,2*pi,length.out=100)),  -->
<!--                    y = 1+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[1], -->
<!--                alpha = 0.3) +  -->
<!--   # Ranking -->
<!--   geom_polygon(aes(x = -0.75+1*cos(seq(0,2*pi,length.out=100)), -->
<!--                    y = 2.25+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[2], -->
<!--                alpha = 0.3) +  -->
<!--   # Unfavorable Outcome -->
<!--   geom_polygon(aes(x = 0.75+1*cos(seq(0,2*pi,length.out=100)), -->
<!--                    y = 2.25+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[3], -->
<!--                alpha = 0.3) +  -->
<!--   annotate(geom = "text", x = 1.5, y = 3, hjust = 0, label = "Unfavorable Outcome", size = 5) +  -->
<!--   annotate(geom = "text", x = -1.5, y = 3, hjust = 1, label = "Ranking", size = 5) +  -->
<!--   annotate(geom = "text", x = 0, y = 0, vjust = 1.1, label = "TPP", size = 5) +  -->
<!--   coord_fixed(xlim = c(-3,3), -->
<!--               ylim = c(-0.5, 3.5)) + -->
<!--   annotate(geom = "text", x = 0.75, y = 2.25, label = round(100*p_df_2$only.relapse, 1), size = 5) + -->
<!--   annotate(geom = "text", x = -0.75, y = 2.25, label = round(100*p_df_2$only.rank, 1), size = 5) + -->
<!--   annotate(geom = "text", x = 0, y = 1, label = round(100*p_df_2$only.TPP, 1), size = 5) + -->
<!--   annotate(geom = "text", x = -0.375, y = 1.55, hjust = 1, label = round(100*p_df_2$agree.TPP.rank, 1)) + -->
<!--   annotate(geom = "text", x = 0.375, y = 1.55, hjust = 0, label = round(100*p_df_2$agree.relapse.TPP, 3)) + -->
<!--   annotate(geom = "text", x = 0, y = 1.85, label = round(100*p_df_2$agree.all, 1)) + -->
<!--   annotate(geom = "text", x = 0, y = 2.25, label = round(100*p_df_2$agree.relapse.rank, 1)) + -->
<!--   ggpubr::theme_pubr() +  -->
<!--   labs(caption = paste0("Sub-optimal regimens missed: ", round(p_df_2$p.missed*100, 2), "%")) + -->
<!--   theme(axis.line = element_blank(), -->
<!--         axis.text = element_blank(), -->
<!--         axis.title = element_blank(), -->
<!--         axis.ticks = element_blank(), -->
<!--         plot.title = element_text(hjust = 0.5)) +  -->
<!--   ggtitle("10% Relative Slope, TTP") -->

<!-- p3 <- ggplot() +  -->
<!--   # TPP -->
<!--   geom_polygon(aes(x = 0+1*cos(seq(0,2*pi,length.out=100)),  -->
<!--                    y = 1+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[1], -->
<!--                alpha = 0.3) +  -->
<!--   # Ranking -->
<!--   geom_polygon(aes(x = -0.75+1*cos(seq(0,2*pi,length.out=100)), -->
<!--                    y = 2.25+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[2], -->
<!--                alpha = 0.3) +  -->
<!--   # Unfavorable Outcome -->
<!--   geom_polygon(aes(x = 0.75+1*cos(seq(0,2*pi,length.out=100)), -->
<!--                    y = 2.25+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[3], -->
<!--                alpha = 0.3) +  -->
<!--   annotate(geom = "text", x = 1.5, y = 3, hjust = 0, label = "Unfavorable Outcome", size = 5) +  -->
<!--   annotate(geom = "text", x = -1.5, y = 3, hjust = 1, label = "Ranking", size = 5) +  -->
<!--   annotate(geom = "text", x = 0, y = 0, vjust = 1.1, label = "TPP", size = 5) +  -->
<!--   coord_fixed(xlim = c(-3,3), -->
<!--               ylim = c(-0.5, 3.5)) + -->
<!--   annotate(geom = "text", x = 0.75, y = 2.25, label = round(100*p_df_3$only.relapse, 1), size = 5) + -->
<!--   annotate(geom = "text", x = -0.75, y = 2.25, label = round(100*p_df_3$only.rank, 1), size = 5) + -->
<!--   annotate(geom = "text", x = 0, y = 1, label = round(100*p_df_3$only.TPP, 1), size = 5) + -->
<!--   annotate(geom = "text", x = -0.375, y = 1.55, hjust = 1, label = round(100*p_df_3$agree.TPP.rank, 1)) + -->
<!--   annotate(geom = "text", x = 0.375, y = 1.55, hjust = 0, label = round(100*p_df_3$agree.relapse.TPP, 1)) + -->
<!--   annotate(geom = "text", x = 0, y = 1.85, label = round(100*p_df_3$agree.all, 1)) + -->
<!--   annotate(geom = "text", x = 0, y = 2.25, label = round(100*p_df_3$agree.relapse.rank, 1)) + -->
<!--   ggpubr::theme_pubr() +  -->
<!--   labs(caption = paste0("Sub-optimal regimens missed: ", round(p_df_3$p.missed*100, 2), "%")) + -->
<!--   theme(axis.line = element_blank(), -->
<!--         axis.text = element_blank(), -->
<!--         axis.title = element_blank(), -->
<!--         axis.ticks = element_blank(), -->
<!--         plot.title = element_text(hjust = 0.5)) +  -->
<!--   ggtitle("20% Relative Slope, TTP") -->

<!-- ggpubr::ggarrange(p1, p2, p3, nrow = 1) -->
<!-- # desirable regimens (relapse) -->
<!-- # prop stopped relapse, prop GO/Continue -->
<!-- ``` -->

<!-- ```{r eval = FALSE} -->
<!-- ggsave(filename = here("graphs", "simulation-results", "random-intercept-random-slope", -->
<!--                               paste0(Sys.Date(), "_venn-diagram_all-together_sub-optimal-nk30.png")), -->
<!--        height = 5, -->
<!--        width = 12,  -->
<!--        units = "in", -->
<!--        device = "png") -->
<!-- ``` -->

<!-- ### De-prioritizing sub-optimal regimens -->

<!-- De-prioritizing based on:     -->

<!-- + TTP decision: NO-GO, **Continue** -->
<!-- + P(rank in top 2) < 60% -->
<!-- + Unfavorable Outcomes >= 2 -->

<!-- ```{r} -->
<!-- t1 <- out_hl_30_r1 %>%  -->
<!--   summarise(`Stop relapse` = mean(n_relapse_interim1 >= 2), -->
<!--             `Stop TPP` = mean(Decision == "NO-GO" | Decision == "Continue"), -->
<!--             `P(top 2) < 0.6` = mean(p.subset.2 < 0.6), -->
<!--             `Stop relapse or TPP` = mean((n_relapse_interim1 >= 2) | (Decision == "NO-GO") | (Decision == "Continue")), -->
<!--             `Stop relapse or TPP or P(top 2) < 0.6` = mean((n_relapse_interim1 >= 2) | (Decision == "NO-GO") | mean(p.subset.2 < 0.6) | (Decision == "Continue"))) %>%  -->
<!--   mutate(Slope = "-10%", .before = 1) -->

<!-- t2 <- out_hl_30_r2 %>%  -->
<!--   summarise(`Stop relapse` = mean(n_relapse_interim1 >= 2), -->
<!--             `Stop TPP` = mean(Decision == "NO-GO" | Decision == "Continue"), -->
<!--             `P(top 2) < 0.6` = mean(p.subset.2 < 0.6), -->
<!--             `Stop relapse or TPP` = mean((n_relapse_interim1 >= 2) | (Decision == "NO-GO") | (Decision == "Continue")), -->
<!--             `Stop relapse or TPP or P(top 2) < 0.6` = mean((n_relapse_interim1 >= 2) | (Decision == "NO-GO") | mean(p.subset.2 < 0.6) | (Decision == "Continue"))) %>%  -->
<!--   mutate(Slope = "10%", .before = 1) -->

<!-- t3 <- out_hl_30_r3 %>%  -->
<!--   summarise(`Stop relapse` = mean(n_relapse_interim1 >= 2), -->
<!--             `Stop TPP` = mean(Decision == "NO-GO" | Decision == "Continue"), -->
<!--             `P(top 2) < 0.6` = mean(p.subset.2 < 0.6), -->
<!--             `Stop relapse or TPP` = mean((n_relapse_interim1 >= 2) | (Decision == "NO-GO") | (Decision == "Continue")), -->
<!--             `Stop relapse or TPP or P(top 2) < 0.6` = mean((n_relapse_interim1 >= 2) | (Decision == "NO-GO") | mean(p.subset.2 < 0.6) | (Decision == "Continue"))) %>%  -->
<!--   mutate(Slope = "20%", .before = 1) -->

<!-- bind_rows(t1, t2, t3) %>%  -->
<!--   kable(digits = 3) %>%  -->
<!--   kable_styling() -->

<!-- p_df <- data.frame(relapse = ifelse(out_hl_30_r1$n_relapse_interim1 >= 2, "NO-GO", "Other"), -->
<!--                    TPP = ifelse(out_hl_30_r1$Decision == "GO", "Other", "NO-GO"), -->
<!--                    ranking = ifelse(out_hl_30_r1$p.subset.2 <= 0.6, "NO-GO", "Other")) %>%  -->
<!--   summarise(agree.relapse.rank = mean((relapse == ranking) & (relapse == "NO-GO") & (TPP == "Other")), -->
<!--             agree.relapse.TPP = mean((relapse == TPP) & (relapse == "NO-GO") & (ranking == "Other")), -->
<!--             agree.TPP.rank = mean((TPP == ranking) & (ranking == "NO-GO") & (relapse == "Other")), -->
<!--             agree.all = mean((TPP == ranking) & (TPP == relapse) & (relapse == "NO-GO")), -->
<!--             only.relapse = mean((relapse == "NO-GO") & (TPP == "Other") & (ranking == "Other")), -->
<!--             only.TPP = mean((TPP == "NO-GO") & (ranking == "Other") & (relapse == "Other")), -->
<!--             only.rank = mean((ranking == "NO-GO") & (TPP == "Other") & (relapse == "Other")), -->
<!--             p.missed = mean(relapse == "Other" & ranking == "Other" & TPP == "Other")) -->
<!-- p_df_2 <- data.frame(relapse = ifelse(out_hl_30_r2$n_relapse_interim1 >= 2, "NO-GO", "Other"), -->
<!--                  TPP = ifelse(out_hl_30_r2$Decision == "GO", "Other", "NO-GO"), -->
<!--                  ranking = ifelse(out_hl_30_r2$p.subset.2 <= 0.6, "NO-GO", "Other")) %>%  -->
<!--   summarise(agree.relapse.rank = mean((relapse == ranking) & (relapse == "NO-GO") & (TPP == "Other")), -->
<!--             agree.relapse.TPP = mean((relapse == TPP) & (relapse == "NO-GO") & (ranking == "Other")), -->
<!--             agree.TPP.rank = mean((TPP == ranking) & (ranking == "NO-GO") & (relapse == "Other")), -->
<!--             agree.all = mean((TPP == ranking) & (TPP == relapse) & (relapse == "NO-GO")), -->
<!--             only.relapse = mean((relapse == "NO-GO") & (TPP == "Other") & (ranking == "Other")), -->
<!--             only.TPP = mean((TPP == "NO-GO") & (ranking == "Other") & (relapse == "Other")), -->
<!--             only.rank = mean((ranking == "NO-GO") & (TPP == "Other") & (relapse == "Other")), -->
<!--             p.missed = mean(relapse == "Other" & ranking == "Other" & TPP == "Other")) -->
<!-- p_df_3 <- data.frame(relapse = ifelse(out_hl_30_r3$n_relapse_interim1 >= 2, "NO-GO", "Other"), -->
<!--                  TPP = ifelse(out_hl_30_r3$Decision == "GO", "Other", "NO-GO"), -->
<!--                  ranking = ifelse(out_hl_30_r3$p.subset.2 <= 0.6, "NO-GO", "Other")) %>%  -->
<!--   summarise(agree.relapse.rank = mean((relapse == ranking) & (relapse == "NO-GO") & (TPP == "Other")), -->
<!--             agree.relapse.TPP = mean((relapse == TPP) & (relapse == "NO-GO") & (ranking == "Other")), -->
<!--             agree.TPP.rank = mean((TPP == ranking) & (ranking == "NO-GO") & (relapse == "Other")), -->
<!--             agree.all = mean((TPP == ranking) & (TPP == relapse) & (relapse == "NO-GO")), -->
<!--             only.relapse = mean((relapse == "NO-GO") & (TPP == "Other") & (ranking == "Other")), -->
<!--             only.TPP = mean((TPP == "NO-GO") & (ranking == "Other") & (relapse == "Other")), -->
<!--             only.rank = mean((ranking == "NO-GO") & (TPP == "Other") & (relapse == "Other")), -->
<!--             p.missed = mean(relapse == "Other" & ranking == "Other" & TPP == "Other")) -->


<!-- p1 <- ggplot() +  -->
<!--    # TPP -->
<!--   geom_polygon(aes(x = 0+1*cos(seq(0,2*pi,length.out=100)),  -->
<!--                    y = 1+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[1], -->
<!--                alpha = 0.3) +  -->
<!--   # Ranking -->
<!--   geom_polygon(aes(x = -0.75+1*cos(seq(0,2*pi,length.out=100)), -->
<!--                    y = 1.95+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[2], -->
<!--                alpha = 0.3) +  -->
<!--   # Unfavorable Outcome -->
<!--   geom_polygon(aes(x = 0.75+1*cos(seq(0,2*pi,length.out=100)), -->
<!--                    y = 1.95+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[3], -->
<!--                alpha = 0.3) +  -->
<!--   annotate(geom = "text", x = 1.5, y = 3, hjust = 0, label = "Unfavorable\n  Outcome", size = 4.5, vjust = 1) +  -->
<!--   annotate(geom = "text", x = -1.5, y = 3, hjust = 1, label = "Ranking", size = 4.5, vjust = 1) +  -->
<!--   annotate(geom = "text", x = 0, y = 0, vjust = 1.1, label = "TPP", size = 4.5) +  -->
<!--   coord_fixed(xlim = c(-3,3), -->
<!--               ylim = c(-0.5, 3.5)) + -->
<!--   annotate(geom = "text", x = 0.95, y = 2.25, label = round(100*p_df$only.relapse, 1), size = 5) + -->
<!--   annotate(geom = "text", x = -0.95, y = 2.25, label = round(100*p_df$only.rank, 1), size = 5) + -->
<!--   annotate(geom = "text", x = 0, y = 0.5, label = round(100*p_df$only.TPP, 1), size = 5) + -->
<!--   annotate(geom = "text", x = -0.35, y = 1.325, hjust = 1, label = round(100*p_df$agree.TPP.rank, 1)) + -->
<!--   annotate(geom = "text", x = 0.35, y = 1.325, hjust = 0, label = round(100*p_df$agree.relapse.TPP, 1)) + -->
<!--   annotate(geom = "text", x = 0, y = 1.7, label = round(100*p_df$agree.all, 1)) + -->
<!--   annotate(geom = "text", x = 0, y = 2.225, label = round(100*p_df$agree.relapse.rank, 1)) + -->
<!--   ggpubr::theme_pubr() +  -->
<!--   labs(caption = paste0("Sub-optimal regimens missed: ", round(p_df$p.missed*100, 2), "%")) + -->
<!--   theme(axis.line = element_blank(), -->
<!--         axis.text = element_blank(), -->
<!--         axis.title = element_blank(), -->
<!--         axis.ticks = element_blank(), -->
<!--         plot.title = element_text(hjust = 0.5)) +  -->
<!--   ggtitle("-10% Relative Slope, TTP") -->

<!-- p2 <- ggplot() +  -->
<!--   # TPP -->
<!--   geom_polygon(aes(x = 0+1*cos(seq(0,2*pi,length.out=100)),  -->
<!--                    y = 1+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[1], -->
<!--                alpha = 0.3) +  -->
<!--   # Ranking -->
<!--   geom_polygon(aes(x = -0.75+1*cos(seq(0,2*pi,length.out=100)), -->
<!--                    y = 1.95+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[2], -->
<!--                alpha = 0.3) +  -->
<!--   # Unfavorable Outcome -->
<!--   geom_polygon(aes(x = 0.75+1*cos(seq(0,2*pi,length.out=100)), -->
<!--                    y = 1.95+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[3], -->
<!--                alpha = 0.3) +  -->
<!--   annotate(geom = "text", x = 1.5, y = 3, hjust = 0, label = "Unfavorable\n  Outcome", size = 4.5, vjust = 1) +  -->
<!--   annotate(geom = "text", x = -1.5, y = 3, hjust = 1, label = "Ranking", size = 4.5, vjust = 1) +  -->
<!--   annotate(geom = "text", x = 0, y = 0, vjust = 1.1, label = "TPP", size = 4.5) +  -->
<!--   coord_fixed(xlim = c(-3,3), -->
<!--               ylim = c(-0.5, 3.5)) + -->
<!--   annotate(geom = "text", x = 0.95, y = 2.25, label = round(100*p_df_2$only.relapse, 1), size = 6) + -->
<!--   annotate(geom = "text", x = -0.95, y = 2.25, label = round(100*p_df_2$only.rank, 1), size = 6) + -->
<!--   annotate(geom = "text", x = 0, y = 0.5, label = round(100*p_df_2$only.TPP, 1), size = 6) + -->
<!--   annotate(geom = "text", x = -0.35, y = 1.325, hjust = 1, label = round(100*p_df_2$agree.TPP.rank, 1)) + -->
<!--   annotate(geom = "text", x = 0.35, y = 1.325, hjust = 0, label = round(100*p_df_2$agree.relapse.TPP, 3)) + -->
<!--   annotate(geom = "text", x = 0, y = 1.7, label = round(100*p_df_2$agree.all, 1)) + -->
<!--   annotate(geom = "text", x = 0, y = 2.225, label = round(100*p_df_2$agree.relapse.rank, 1)) + -->
<!--   ggpubr::theme_pubr() +  -->
<!--   labs(caption = paste0("Sub-optimal regimens missed: ", round(p_df_2$p.missed*100, 2), "%")) + -->
<!--   theme(axis.line = element_blank(), -->
<!--         axis.text = element_blank(), -->
<!--         axis.title = element_blank(), -->
<!--         axis.ticks = element_blank(), -->
<!--         plot.title = element_text(hjust = 0.5)) +  -->
<!--   ggtitle("10% Relative Slope, TTP") -->

<!-- p3 <- ggplot() +  -->
<!--   # TPP -->
<!--   geom_polygon(aes(x = 0+1*cos(seq(0,2*pi,length.out=100)),  -->
<!--                    y = 1+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[1], -->
<!--                alpha = 0.3) +  -->
<!--   # Ranking -->
<!--   geom_polygon(aes(x = -0.75+1*cos(seq(0,2*pi,length.out=100)), -->
<!--                    y = 1.95+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[2], -->
<!--                alpha = 0.3) +  -->
<!--   # Unfavorable Outcome -->
<!--   geom_polygon(aes(x = 0.75+1*cos(seq(0,2*pi,length.out=100)), -->
<!--                    y = 1.95+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[3], -->
<!--                alpha = 0.3) +  -->
<!--   annotate(geom = "text", x = 1.5, y = 3, hjust = 0, label = "Unfavorable\n  Outcome", size = 4.5, vjust = 1) +  -->
<!--   annotate(geom = "text", x = -1.5, y = 3, hjust = 1, label = "Ranking", size = 4.5, vjust = 1) +  -->
<!--   annotate(geom = "text", x = 0, y = 0, vjust = 1.1, label = "TPP", size = 4.5) +  -->
<!--   coord_fixed(xlim = c(-3,3), -->
<!--               ylim = c(-0.5, 3.5)) + -->
<!--   annotate(geom = "text", x = 0.95, y = 2.25, label = round(100*p_df_3$only.relapse, 1), size = 6) + -->
<!--   annotate(geom = "text", x = -0.95, y = 2.25, label = round(100*p_df_3$only.rank, 1), size = 6) + -->
<!--   annotate(geom = "text", x = 0, y = 0.5, label = round(100*p_df_3$only.TPP, 1), size = 6) + -->
<!--   annotate(geom = "text", x = -0.35, y = 1.325, hjust = 1, label = round(100*p_df_3$agree.TPP.rank, 1)) + -->
<!--   annotate(geom = "text", x = 0.35, y = 1.325, hjust = 0, label = round(100*p_df_3$agree.relapse.TPP, 1)) + -->
<!--   annotate(geom = "text", x = 0, y = 1.7, label = round(100*p_df_3$agree.all, 1)) + -->
<!--   annotate(geom = "text", x = 0, y = 2.225, label = round(100*p_df_3$agree.relapse.rank, 1)) + -->
<!--   ggpubr::theme_pubr() +  -->
<!--   labs(caption = paste0("Sub-optimal regimens missed: ", round(p_df_3$p.missed*100, 2), "%")) + -->
<!--   theme(axis.line = element_blank(), -->
<!--         axis.text = element_blank(), -->
<!--         axis.title = element_blank(), -->
<!--         axis.ticks = element_blank(), -->
<!--         plot.title = element_text(hjust = 0.5)) +  -->
<!--   ggtitle("20% Relative Slope, TTP") -->

<!-- p1 + p2 + p3 +  -->
<!--   plot_annotation(tag_levels = "A") -->
<!-- ``` -->

<!-- ```{r eval = FALSE} -->
<!-- ggsave(filename = here("graphs", "simulation-results", "random-intercept-random-slope", -->
<!--                               paste0(Sys.Date(), "_venn-diagram_all-together_sub-optimal-2-nk30.png")), -->
<!--        height = 5, -->
<!--        width = 12,  -->
<!--        units = "in", -->
<!--        device = "png") -->
<!-- ``` -->

<!-- ### De-prioritizing sub-optimal regimens (NEW) -->

<!-- De-prioritizing based on:     -->

<!-- + TTP decision: NO-GO, **Continue** -->
<!-- + P(rank in top 2) < 60% -->
<!-- + Unfavorable Outcomes >= 2 -->

<!-- ```{r} -->
<!-- ###################### -->
<!-- # Regimen 2 (Sub-optimal relapses) -->
<!-- ###################### -->

<!-- # TPP decision -->
<!-- out_hl_30_tpp_r1 <- decisions$decisions_highlow %>% # -10% slope -->
<!--   filter(Regimen == "Regimen 1", nk == 30) %>% # indexing sets control at 0 -->
<!--   dplyr::select(-Regimen) -->
<!-- out_hl_30_tpp_r2 <- decisions$decisions_highlow %>% # 10% slope -->
<!--   filter(Regimen == "Regimen 2", nk == 30) %>% # indexing sets control at 0 -->
<!--   dplyr::select(-Regimen) -->
<!-- out_hl_30_tpp_r3 <- decisions$decisions_highlow %>% # 35% slope -->
<!--   filter(Regimen == "Regimen 3", nk == 30) %>% # indexing sets control at 0 -->
<!--   dplyr::select(-Regimen) -->

<!-- # Ranking -->
<!-- out_hl_30_ranking_r1 <- map_dfr(filter(ranking_probabilities$highlow_probabilities, nk == 30), -->
<!--                              ~.x, .id = "sim") %>%  -->
<!--   filter(regimen == "arm2") %>% # -10% slope -->
<!--   dplyr::select(-regimen) -->
<!-- out_hl_30_ranking_r2 <- map_dfr(filter(ranking_probabilities$highlow_probabilities, nk == 30), -->
<!--                              ~.x, .id = "sim") %>%  -->
<!--   filter(regimen == "arm3") %>% # 10% slope -->
<!--   dplyr::select(-regimen) -->
<!-- out_hl_30_ranking_r3 <- map_dfr(filter(ranking_probabilities$highlow_probabilities, nk == 30), -->
<!--                              ~.x, .id = "sim") %>%  -->
<!--   filter(regimen == "arm4") %>% # 35% slope -->
<!--   dplyr::select(-regimen) -->

<!-- out_hl_30_r1 <- full_join( -->
<!--   full_join(out_hl_30_relapse_r1, out_hl_30_tpp_r1),  -->
<!--                        out_hl_30_ranking_r1) -->
<!-- out_hl_30_r2 <- full_join( -->
<!--   full_join(out_hl_30_relapse_r2, out_hl_30_tpp_r2),  -->
<!--                        out_hl_30_ranking_r2) -->
<!-- out_hl_30_r3 <- full_join( -->
<!--   full_join(out_hl_30_relapse_r3, out_hl_30_tpp_r3),  -->
<!--                        out_hl_30_ranking_r3) -->

<!-- t1 <- out_hl_30_r1 %>%  -->
<!--   summarise(`Stop relapse` = mean(n_relapse_interim1 >= 2), -->
<!--             `Stop TPP` = mean(Decision == "NO-GO" | Decision == "Continue"), -->
<!--             `P(top 2) < 0.6` = mean(p.subset.2 < 0.6), -->
<!--             `Stop relapse or TPP` = mean((n_relapse_interim1 >= 2) | (Decision == "NO-GO") | (Decision == "Continue")), -->
<!--             `Stop relapse or TPP or P(top 2) < 0.6` = mean((n_relapse_interim1 >= 2) | (Decision == "NO-GO") | mean(p.subset.2 < 0.6) | (Decision == "Continue"))) %>%  -->
<!--   mutate(Slope = "-10%", .before = 1) -->

<!-- t2 <- out_hl_30_r2 %>%  -->
<!--   summarise(`Stop relapse` = mean(n_relapse_interim1 >= 2), -->
<!--             `Stop TPP` = mean(Decision == "NO-GO" | Decision == "Continue"), -->
<!--             `P(top 2) < 0.6` = mean(p.subset.2 < 0.6), -->
<!--             `Stop relapse or TPP` = mean((n_relapse_interim1 >= 2) | (Decision == "NO-GO") | (Decision == "Continue")), -->
<!--             `Stop relapse or TPP or P(top 2) < 0.6` = mean((n_relapse_interim1 >= 2) | (Decision == "NO-GO") | mean(p.subset.2 < 0.6) | (Decision == "Continue"))) %>%  -->
<!--   mutate(Slope = "10%", .before = 1) -->

<!-- t3 <- out_hl_30_r3 %>%  -->
<!--   summarise(`Stop relapse` = mean(n_relapse_interim1 >= 2), -->
<!--             `Stop TPP` = mean(Decision == "NO-GO" | Decision == "Continue"), -->
<!--             `P(top 2) < 0.6` = mean(p.subset.2 < 0.6), -->
<!--             `Stop relapse or TPP` = mean((n_relapse_interim1 >= 2) | (Decision == "NO-GO") | (Decision == "Continue")), -->
<!--             `Stop relapse or TPP or P(top 2) < 0.6` = mean((n_relapse_interim1 >= 2) | (Decision == "NO-GO") | mean(p.subset.2 < 0.6) | (Decision == "Continue"))) %>%  -->
<!--   mutate(Slope = "35%", .before = 1) -->

<!-- bind_rows(t1, t2, t3) %>%  -->
<!--   kable(digits = 3) %>%  -->
<!--   kable_styling() -->

<!-- p_df <- data.frame(relapse = ifelse(out_hl_30_r1$n_relapse_interim1 >= 2, "NO-GO", "Other"), -->
<!--                    TPP = ifelse(out_hl_30_r1$Decision == "GO", "Other", "NO-GO"), -->
<!--                    ranking = ifelse(out_hl_30_r1$p.subset.2 <= 0.6, "NO-GO", "Other")) %>%  -->
<!--   summarise(agree.relapse.rank = mean((relapse == ranking) & (relapse == "NO-GO") & (TPP == "Other")), -->
<!--             agree.relapse.TPP = mean((relapse == TPP) & (relapse == "NO-GO") & (ranking == "Other")), -->
<!--             agree.TPP.rank = mean((TPP == ranking) & (ranking == "NO-GO") & (relapse == "Other")), -->
<!--             agree.all = mean((TPP == ranking) & (TPP == relapse) & (relapse == "NO-GO")), -->
<!--             only.relapse = mean((relapse == "NO-GO") & (TPP == "Other") & (ranking == "Other")), -->
<!--             only.TPP = mean((TPP == "NO-GO") & (ranking == "Other") & (relapse == "Other")), -->
<!--             only.rank = mean((ranking == "NO-GO") & (TPP == "Other") & (relapse == "Other")), -->
<!--             p.missed = mean(relapse == "Other" & ranking == "Other" & TPP == "Other")) -->
<!-- p_df_2 <- data.frame(relapse = ifelse(out_hl_30_r2$n_relapse_interim1 >= 2, "NO-GO", "Other"), -->
<!--                  TPP = ifelse(out_hl_30_r2$Decision == "GO", "Other", "NO-GO"), -->
<!--                  ranking = ifelse(out_hl_30_r2$p.subset.2 <= 0.6, "NO-GO", "Other")) %>%  -->
<!--   summarise(agree.relapse.rank = mean((relapse == ranking) & (relapse == "NO-GO") & (TPP == "Other")), -->
<!--             agree.relapse.TPP = mean((relapse == TPP) & (relapse == "NO-GO") & (ranking == "Other")), -->
<!--             agree.TPP.rank = mean((TPP == ranking) & (ranking == "NO-GO") & (relapse == "Other")), -->
<!--             agree.all = mean((TPP == ranking) & (TPP == relapse) & (relapse == "NO-GO")), -->
<!--             only.relapse = mean((relapse == "NO-GO") & (TPP == "Other") & (ranking == "Other")), -->
<!--             only.TPP = mean((TPP == "NO-GO") & (ranking == "Other") & (relapse == "Other")), -->
<!--             only.rank = mean((ranking == "NO-GO") & (TPP == "Other") & (relapse == "Other")), -->
<!--             p.missed = mean(relapse == "Other" & ranking == "Other" & TPP == "Other")) -->
<!-- p_df_3 <- data.frame(relapse = ifelse(out_hl_30_r3$n_relapse_interim1 >= 2, "NO-GO", "Other"), -->
<!--                  TPP = ifelse(out_hl_30_r3$Decision == "GO", "Other", "NO-GO"), -->
<!--                  ranking = ifelse(out_hl_30_r3$p.subset.2 <= 0.6, "NO-GO", "Other")) %>%  -->
<!--   summarise(agree.relapse.rank = mean((relapse == ranking) & (relapse == "NO-GO") & (TPP == "Other")), -->
<!--             agree.relapse.TPP = mean((relapse == TPP) & (relapse == "NO-GO") & (ranking == "Other")), -->
<!--             agree.TPP.rank = mean((TPP == ranking) & (ranking == "NO-GO") & (relapse == "Other")), -->
<!--             agree.all = mean((TPP == ranking) & (TPP == relapse) & (relapse == "NO-GO")), -->
<!--             only.relapse = mean((relapse == "NO-GO") & (TPP == "Other") & (ranking == "Other")), -->
<!--             only.TPP = mean((TPP == "NO-GO") & (ranking == "Other") & (relapse == "Other")), -->
<!--             only.rank = mean((ranking == "NO-GO") & (TPP == "Other") & (relapse == "Other")), -->
<!--             p.missed = mean(relapse == "Other" & ranking == "Other" & TPP == "Other")) -->

<!-- p1 <- ggplot() +  -->
<!--    # TPP -->
<!--   geom_polygon(aes(x = 0+1*cos(seq(0,2*pi,length.out=100)),  -->
<!--                    y = 1+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[1], -->
<!--                alpha = 0.3) +  -->
<!--   # Ranking -->
<!--   geom_polygon(aes(x = -0.75+1*cos(seq(0,2*pi,length.out=100)), -->
<!--                    y = 1.95+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[2], -->
<!--                alpha = 0.3) +  -->
<!--   # Unfavorable Outcome -->
<!--   geom_polygon(aes(x = 0.75+1*cos(seq(0,2*pi,length.out=100)), -->
<!--                    y = 1.95+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[3], -->
<!--                alpha = 0.3) +  -->
<!--   annotate(geom = "text", x = 1.5, y = 3, hjust = 0, label = "Unfavorable\n  Outcome", size = 4.5, vjust = 1) +  -->
<!--   annotate(geom = "text", x = -1.5, y = 3, hjust = 1, label = "Ranking", size = 4.5, vjust = 1) +  -->
<!--   annotate(geom = "text", x = 0, y = 0, vjust = 1.1, label = "TPP", size = 4.5) +  -->
<!--   coord_fixed(xlim = c(-3,3), -->
<!--               ylim = c(-0.5, 3.5)) + -->
<!--   annotate(geom = "text", x = 0.95, y = 2.25, label = round(100*p_df$only.relapse, 1), size = 5) + -->
<!--   annotate(geom = "text", x = -0.95, y = 2.25, label = round(100*p_df$only.rank, 1), size = 5) + -->
<!--   annotate(geom = "text", x = 0, y = 0.5, label = round(100*p_df$only.TPP, 1), size = 5) + -->
<!--   annotate(geom = "text", x = -0.35, y = 1.325, hjust = 1, label = round(100*p_df$agree.TPP.rank, 1)) + -->
<!--   annotate(geom = "text", x = 0.35, y = 1.325, hjust = 0, label = round(100*p_df$agree.relapse.TPP, 1)) + -->
<!--   annotate(geom = "text", x = 0, y = 1.7, label = round(100*p_df$agree.all, 1)) + -->
<!--   annotate(geom = "text", x = 0, y = 2.225, label = round(100*p_df$agree.relapse.rank, 1)) + -->
<!--   ggpubr::theme_pubr() +  -->
<!--   labs(caption = paste0("Sub-optimal regimens missed: ", round(p_df$p.missed*100, 2), "%")) + -->
<!--   theme(axis.line = element_blank(), -->
<!--         axis.text = element_blank(), -->
<!--         axis.title = element_blank(), -->
<!--         axis.ticks = element_blank(), -->
<!--         plot.title = element_text(hjust = 0.5)) +  -->
<!--   ggtitle("-10% Relative Slope, TTP") -->

<!-- p2 <- ggplot() +  -->
<!--   # TPP -->
<!--   geom_polygon(aes(x = 0+1*cos(seq(0,2*pi,length.out=100)),  -->
<!--                    y = 1+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[1], -->
<!--                alpha = 0.3) +  -->
<!--   # Ranking -->
<!--   geom_polygon(aes(x = -0.75+1*cos(seq(0,2*pi,length.out=100)), -->
<!--                    y = 1.95+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[2], -->
<!--                alpha = 0.3) +  -->
<!--   # Unfavorable Outcome -->
<!--   geom_polygon(aes(x = 0.75+1*cos(seq(0,2*pi,length.out=100)), -->
<!--                    y = 1.95+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[3], -->
<!--                alpha = 0.3) +  -->
<!--   annotate(geom = "text", x = 1.5, y = 3, hjust = 0, label = "Unfavorable\n  Outcome", size = 4.5, vjust = 1) +  -->
<!--   annotate(geom = "text", x = -1.5, y = 3, hjust = 1, label = "Ranking", size = 4.5, vjust = 1) +  -->
<!--   annotate(geom = "text", x = 0, y = 0, vjust = 1.1, label = "TPP", size = 4.5) +  -->
<!--   coord_fixed(xlim = c(-3,3), -->
<!--               ylim = c(-0.5, 3.5)) + -->
<!--   annotate(geom = "text", x = 0.95, y = 2.25, label = round(100*p_df_2$only.relapse, 1), size = 6) + -->
<!--   annotate(geom = "text", x = -0.95, y = 2.25, label = round(100*p_df_2$only.rank, 1), size = 6) + -->
<!--   annotate(geom = "text", x = 0, y = 0.5, label = round(100*p_df_2$only.TPP, 1), size = 6) + -->
<!--   annotate(geom = "text", x = -0.35, y = 1.325, hjust = 1, label = round(100*p_df_2$agree.TPP.rank, 1)) + -->
<!--   annotate(geom = "text", x = 0.35, y = 1.325, hjust = 0, label = round(100*p_df_2$agree.relapse.TPP, 3)) + -->
<!--   annotate(geom = "text", x = 0, y = 1.7, label = round(100*p_df_2$agree.all, 1)) + -->
<!--   annotate(geom = "text", x = 0, y = 2.225, label = round(100*p_df_2$agree.relapse.rank, 1)) + -->
<!--   ggpubr::theme_pubr() +  -->
<!--   labs(caption = paste0("Sub-optimal regimens missed: ", round(p_df_2$p.missed*100, 2), "%")) + -->
<!--   theme(axis.line = element_blank(), -->
<!--         axis.text = element_blank(), -->
<!--         axis.title = element_blank(), -->
<!--         axis.ticks = element_blank(), -->
<!--         plot.title = element_text(hjust = 0.5)) +  -->
<!--   ggtitle("10% Relative Slope, TTP") -->

<!-- p3 <- ggplot() +  -->
<!--   # TPP -->
<!--   geom_polygon(aes(x = 0+1*cos(seq(0,2*pi,length.out=100)),  -->
<!--                    y = 1+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[1], -->
<!--                alpha = 0.3) +  -->
<!--   # Ranking -->
<!--   geom_polygon(aes(x = -0.75+1*cos(seq(0,2*pi,length.out=100)), -->
<!--                    y = 1.95+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[2], -->
<!--                alpha = 0.3) +  -->
<!--   # Unfavorable Outcome -->
<!--   geom_polygon(aes(x = 0.75+1*cos(seq(0,2*pi,length.out=100)), -->
<!--                    y = 1.95+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[3], -->
<!--                alpha = 0.3) +  -->
<!--   annotate(geom = "text", x = 1.5, y = 3, hjust = 0, label = "Unfavorable\n  Outcome", size = 4.5, vjust = 1) +  -->
<!--   annotate(geom = "text", x = -1.5, y = 3, hjust = 1, label = "Ranking", size = 4.5, vjust = 1) +  -->
<!--   annotate(geom = "text", x = 0, y = 0, vjust = 1.1, label = "TPP", size = 4.5) +  -->
<!--   coord_fixed(xlim = c(-3,3), -->
<!--               ylim = c(-0.5, 3.5)) + -->
<!--   annotate(geom = "text", x = 0.95, y = 2.25, label = round(100*p_df_3$only.relapse, 1), size = 6) + -->
<!--   annotate(geom = "text", x = -0.95, y = 2.25, label = round(100*p_df_3$only.rank, 1), size = 6) + -->
<!--   annotate(geom = "text", x = 0, y = 0.5, label = round(100*p_df_3$only.TPP, 1), size = 6) + -->
<!--   annotate(geom = "text", x = -0.35, y = 1.325, hjust = 1, label = round(100*p_df_3$agree.TPP.rank, 1)) + -->
<!--   annotate(geom = "text", x = 0.35, y = 1.325, hjust = 0, label = round(100*p_df_3$agree.relapse.TPP, 1)) + -->
<!--   annotate(geom = "text", x = 0, y = 1.7, label = round(100*p_df_3$agree.all, 1)) + -->
<!--   annotate(geom = "text", x = 0, y = 2.225, label = round(100*p_df_3$agree.relapse.rank, 1)) + -->
<!--   ggpubr::theme_pubr() +  -->
<!--   labs(caption = paste0("Sub-optimal regimens missed: ", round(p_df_3$p.missed*100, 2), "%")) + -->
<!--   theme(axis.line = element_blank(), -->
<!--         axis.text = element_blank(), -->
<!--         axis.title = element_blank(), -->
<!--         axis.ticks = element_blank(), -->
<!--         plot.title = element_text(hjust = 0.5)) +  -->
<!--   ggtitle("35% Relative Slope, TTP") -->

<!-- p1 + p2 + p3 +  -->
<!--   plot_annotation(tag_levels = "A") -->
<!-- ``` -->

<!-- ```{r eval = FALSE} -->
<!-- ggsave(filename = here("graphs", "simulation-results", "random-intercept-random-slope", -->
<!--                               paste0(Sys.Date(), "_venn-diagram_all-together_sub-optimal-3-nk30.png")), -->
<!--        height = 5, -->
<!--        width = 12,  -->
<!--        units = "in", -->
<!--        device = "png") -->

<!-- ggsave(filename = here("graphs", "submission", -->
<!--                        "fig-06_venn-diagram_all-together_sub-optimal-3-nk30.tiff"), -->
<!--        height = 5, -->
<!--        width = 12,  -->
<!--        units = "in", -->
<!--        device = "tiff") -->

<!-- p1 + p2 + p3 +  -->
<!--   plot_annotation(tag_levels = "A", -->
<!--                   title = "Dufault Fig. 6 (Top)") -->

<!-- ggsave(filename = here("graphs", "submission", -->
<!--                        "fig-06_venn-diagram_all-together_sub-optimal-3-nk30_annotated.tiff"), -->
<!--        height = 5, -->
<!--        dpi = 600, -->
<!--        width = 12,  -->
<!--        units = "in", -->
<!--        device = "tiff") -->
<!-- ``` -->

<!-- ### Desirable regimens -->

<!-- ```{r data-combined-desirable, eval = TRUE} -->
<!-- ###################### -->
<!-- # Regimen 5 (Desirable) -->
<!-- ###################### -->
<!-- # Situation 2,(ALL Desirable) S(52) = .95 -->
<!-- load(here("data","analyzed","2022-03-07_s95-situation2-results_nk30_4mo-duration.RData")) -->
<!-- s95.sit2.30 <- s95.situation2.results -->
<!-- load(here("data","analyzed","2022-03-07_s95-situation2-results_nk40_4mo-duration.RData")) -->
<!-- s95.sit2.40 <- s95.situation2.results -->
<!-- load(here("data","analyzed","2022-03-07_s95-situation2-results_nk60_4mo-duration.RData")) -->
<!-- s95.sit2.60 <- s95.situation2.results -->
<!-- load(here("data","analyzed","2022-03-07_s95-situation2-results_nk80_4mo-duration.RData")) -->
<!-- s95.sit2.80 <- s95.situation2.results; rm(s95.situation2.results) -->

<!-- # relapses -->
<!-- out_hl_30_relapse_r1 <- s95.sit2.30 %>%  -->
<!--   filter(ttp.condition == "highlow", regimen == "1") %>%  # even though TTP did not play a role in simulating relapse data, a unique relapse dataset was simulated for each unique TTP data (essentially resulting in 3,000 simulated datasets of relapse for each regimen for each condition).  -->
<!--   dplyr::select(-regimen) -->
<!-- out_hl_30_relapse_r2 <- s95.sit2.30 %>%  -->
<!--   filter(ttp.condition == "even", regimen == "1") %>%  # even though TTP did not play a role in simulating relapse data, a unique relapse dataset was simulated for each unique TTP data (essentially resulting in 3,000 simulated datasets of relapse for each regimen for each condition).  -->
<!--   dplyr::select(-regimen) -->
<!-- out_hl_30_relapse_r3 <- s95.sit1.30 %>%  -->
<!--   filter(ttp.condition == "even", regimen == "2") %>%  -->
<!--   dplyr::select(-regimen) -->

<!-- # TPP decision -->
<!-- out_hl_30_tpp_r1 <- decisions$decisions_highlow %>%  -->
<!--   filter(Regimen == "Regimen 1", nk == 30) %>% # -10% -->
<!--   dplyr::select(-Regimen) -->
<!-- out_hl_30_tpp_r2 <- decisions$decisions_even %>%  -->
<!--   filter(Regimen == "Regimen 1", nk == 30) %>% # 10%  -->
<!--   dplyr::select(-Regimen) -->
<!-- out_hl_30_tpp_r3 <- decisions$decisions_even %>%  -->
<!--   filter(Regimen == "Regimen 2", nk == 30) %>% # 20% -->
<!--   dplyr::select(-Regimen) -->

<!-- # Ranking -->
<!-- out_hl_30_ranking_r1 <- map_dfr(filter(ranking_probabilities$highlow_probabilities, nk == 30), -->
<!--                              ~.x, .id = "sim") %>%  -->
<!--   filter(regimen == "arm2") %>%  -->
<!--   dplyr::select(-regimen) -->
<!-- out_hl_30_ranking_r2 <- map_dfr(filter(ranking_probabilities$even_probabilities, nk == 30), -->
<!--                              ~.x, .id = "sim") %>%  -->
<!--   filter(regimen == "arm2") %>%  -->
<!--   dplyr::select(-regimen) -->
<!-- out_hl_30_ranking_r3 <- map_dfr(filter(ranking_probabilities$even_probabilities, nk == 30), -->
<!--                              ~.x, .id = "sim") %>%  -->
<!--   filter(regimen == "arm3") %>%  -->
<!--   dplyr::select(-regimen) -->

<!-- out_hl_30_r1 <- full_join( -->
<!--   full_join(out_hl_30_relapse_r1, out_hl_30_tpp_r1),  -->
<!--                        out_hl_30_ranking_r1) -->
<!-- out_hl_30_r2 <- full_join( -->
<!--   full_join(out_hl_30_relapse_r2, out_hl_30_tpp_r2),  -->
<!--                        out_hl_30_ranking_r2) -->
<!-- out_hl_30_r3 <- full_join( -->
<!--   full_join(out_hl_30_relapse_r3, out_hl_30_tpp_r3),  -->
<!--                        out_hl_30_ranking_r3) -->
<!-- # Table(?)/Heatmap(?) -->
<!-- # focus in on sub-optimal regimens (relapse) -->
<!-- # sample size: 30 -->
<!-- # panels: A) -10%, B) 10%, C) 20% slope -->
<!-- # prop stopped relapse, prop stopped TPP, prop not ranked first or second, prop stopped relapse | prop stopped TPP, prop stopped relapse | prop stopped TPP | not ranked first or second -->

<!-- t1 <- out_hl_30_r1 %>%  -->
<!--   summarise(`GO relapse` = mean(n_relapse_interim1 < 2), -->
<!--             `GO TPP` = mean(Decision == "GO"), -->
<!--             `P(top 2) >= 0.6` = mean(p.subset.2 >= 0.6), -->
<!--             `GO relapse and TPP` = mean((n_relapse_interim1 < 2) & (Decision == "GO")), -->
<!--             `GO relapse and TPP and P(top 2) >= 0.6` = mean((n_relapse_interim1 < 2) & (Decision == "GO") & mean(p.subset.2 >= 0.6))) %>%  -->
<!--   mutate(Slope = "-10%", .before = 1) -->

<!-- t2 <- out_hl_30_r2 %>%  -->
<!--   summarise(`GO relapse` = mean(n_relapse_interim1 < 2), -->
<!--             `GO TPP` = mean(Decision == "GO"), -->
<!--             `P(top 2) >= 0.6` = mean(p.subset.2 >= 0.6), -->
<!--             `GO relapse and TPP` = mean((n_relapse_interim1 < 2) & (Decision == "GO")), -->
<!--             `GO relapse and TPP and P(top 2) >= 0.6` = mean((n_relapse_interim1 < 2) & (Decision == "GO") & mean(p.subset.2 >= 0.6))) %>% -->
<!--   mutate(Slope = "10%", .before = 1) -->

<!-- t3 <- out_hl_30_r3 %>%  -->
<!--   summarise(`GO relapse` = mean(n_relapse_interim1 < 2), -->
<!--             `GO TPP` = mean(Decision == "GO"), -->
<!--             `P(top 2) >= 0.6` = mean(p.subset.2 >= 0.6), -->
<!--             `GO relapse and TPP` = mean((n_relapse_interim1 < 2) & (Decision == "GO")), -->
<!--             `GO relapse and TPP and P(top 2) >= 0.6` = mean((n_relapse_interim1 < 2) & (Decision == "GO") & mean(p.subset.2 >= 0.6))) %>% -->
<!--   mutate(Slope = "20%", .before = 1) -->

<!-- bind_rows(t1, t2, t3) %>%  -->
<!--   kable(digits = 3) %>%  -->
<!--   kable_styling() -->

<!-- p_df <- data.frame(relapse = ifelse(out_hl_30_r1$n_relapse_interim1 < 2, "GO", "Other"), -->
<!--                    TPP = ifelse(out_hl_30_r1$Decision == "GO", "GO", "Other"), -->
<!--                    ranking = ifelse(out_hl_30_r1$p.subset.2 >= 0.6, "GO", "Other")) %>%  -->
<!--    summarise(agree.relapse.rank = mean((relapse == ranking) & (relapse == "GO") & (TPP == "Other")), -->
<!--             agree.relapse.TPP = mean((relapse == TPP) & (relapse == "GO") & (ranking == "Other")), -->
<!--             agree.TPP.rank = mean((TPP == ranking) & (ranking == "GO") & (relapse == "Other")), -->
<!--             agree.all = mean((TPP == ranking) & (TPP == relapse) & (relapse == "GO")), -->
<!--             only.relapse = mean((relapse == "GO") & (TPP == "Other") & (ranking == "Other")), -->
<!--             only.TPP = mean((TPP == "GO") & (ranking == "Other") & (relapse == "Other")), -->
<!--             only.rank = mean((ranking == "GO") & (TPP == "Other") & (relapse == "Other")), -->
<!--             p.missed = mean(relapse == "Other" & ranking == "Other" & TPP == "Other")) -->
<!-- p_df_2 <- data.frame(relapse = ifelse(out_hl_30_r2$n_relapse_interim1 < 2, "GO", "Other"), -->
<!--                  TPP = ifelse(out_hl_30_r2$Decision == "GO", "GO", "Other"), -->
<!--                  ranking = ifelse(out_hl_30_r2$p.subset.2 >= 0.6, "GO", "Other")) %>%  -->
<!--   summarise(agree.relapse.rank = mean((relapse == ranking) & (relapse == "GO") & (TPP == "Other")), -->
<!--             agree.relapse.TPP = mean((relapse == TPP) & (relapse == "GO") & (ranking == "Other")), -->
<!--             agree.TPP.rank = mean((TPP == ranking) & (ranking == "GO") & (relapse == "Other")), -->
<!--             agree.all = mean((TPP == ranking) & (TPP == relapse) & (relapse == "GO")), -->
<!--             only.relapse = mean((relapse == "GO") & (TPP == "Other") & (ranking == "Other")), -->
<!--             only.TPP = mean((TPP == "GO") & (ranking == "Other") & (relapse == "Other")), -->
<!--             only.rank = mean((ranking == "GO") & (TPP == "Other") & (relapse == "Other")), -->
<!--             p.missed = mean(relapse == "Other" & ranking == "Other" & TPP == "Other")) -->
<!-- p_df_3 <- data.frame(relapse = ifelse(out_hl_30_r3$n_relapse_interim1 < 2, "GO", "Other"), -->
<!--                  TPP = ifelse(out_hl_30_r3$Decision == "GO", "GO", "Other"), -->
<!--                  ranking = ifelse(out_hl_30_r3$p.subset.2 >= 0.6, "GO", "Other")) %>%  -->
<!--   summarise(agree.relapse.rank = mean((relapse == ranking) & (relapse == "GO") & (TPP == "Other")), -->
<!--             agree.relapse.TPP = mean((relapse == TPP) & (relapse == "GO") & (ranking == "Other")), -->
<!--             agree.TPP.rank = mean((TPP == ranking) & (ranking == "GO") & (relapse == "Other")), -->
<!--             agree.all = mean((TPP == ranking) & (TPP == relapse) & (relapse == "GO")), -->
<!--             only.relapse = mean((relapse == "GO") & (TPP == "Other") & (ranking == "Other")), -->
<!--             only.TPP = mean((TPP == "GO") & (ranking == "Other") & (relapse == "Other")), -->
<!--             only.rank = mean((ranking == "GO") & (TPP == "Other") & (relapse == "Other")), -->
<!--             p.missed = mean(relapse == "Other" & ranking == "Other" & TPP == "Other")) -->


<!-- p1 <- ggplot() +  -->
<!--   # TPP -->
<!--   geom_polygon(aes(x = 0+1*cos(seq(0,2*pi,length.out=100)),  -->
<!--                    y = 1+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[1], -->
<!--                alpha = 0.3) +  -->
<!--   # Ranking -->
<!--   geom_polygon(aes(x = -0.75+1*cos(seq(0,2*pi,length.out=100)), -->
<!--                    y = 2.25+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[2], -->
<!--                alpha = 0.3) +  -->
<!--   # Unfavorable Outcome -->
<!--   geom_polygon(aes(x = 0.75+1*cos(seq(0,2*pi,length.out=100)), -->
<!--                    y = 2.25+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[3], -->
<!--                alpha = 0.3) +  -->
<!--   annotate(geom = "text", x = 1.5, y = 3, hjust = 0, label = "Unfavorable Outcome", size = 5) +  -->
<!--   annotate(geom = "text", x = -1.5, y = 3, hjust = 1, label = "Ranking", size = 5) +  -->
<!--   annotate(geom = "text", x = 0, y = 0, vjust = 1.1, label = "TPP", size = 5) +  -->
<!--   coord_fixed(xlim = c(-3,3), -->
<!--               ylim = c(-0.5, 3.5)) + -->
<!--   annotate(geom = "text", x = 0.75, y = 2.25, label = round(100*p_df$only.relapse, 1), size = 5) + -->
<!--   annotate(geom = "text", x = -0.75, y = 2.25, label = round(100*p_df$only.rank, 1), size = 5) + -->
<!--   annotate(geom = "text", x = 0, y = 1, label = round(100*p_df$only.TPP, 1), size = 5) + -->
<!--   annotate(geom = "text", x = -0.375, y = 1.55, hjust = 1, label = round(100*p_df$agree.TPP.rank, 1)) + -->
<!--   annotate(geom = "text", x = 0.375, y = 1.55, hjust = 0, label = round(100*p_df$agree.relapse.TPP, 1)) + -->
<!--   annotate(geom = "text", x = 0, y = 1.85, label = round(100*p_df$agree.all, 1)) + -->
<!--   annotate(geom = "text", x = 0, y = 2.25, label = round(100*p_df$agree.relapse.rank, 1)) + -->
<!--   ggpubr::theme_pubr() +  -->
<!--   labs(caption = paste0("Desirable regimens missed: ", round(p_df$p.missed*100, 2), "%")) + -->
<!--   theme(axis.line = element_blank(), -->
<!--         axis.text = element_blank(), -->
<!--         axis.title = element_blank(), -->
<!--         axis.ticks = element_blank(), -->
<!--         plot.title = element_text(hjust = 0.5)) +  -->
<!--   ggtitle("-10% Relative Slope, TTP") -->

<!-- p2 <- ggplot() +  -->
<!--   # TPP -->
<!--   geom_polygon(aes(x = 0+1*cos(seq(0,2*pi,length.out=100)),  -->
<!--                    y = 1+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[1], -->
<!--                alpha = 0.3) +  -->
<!--   # Ranking -->
<!--   geom_polygon(aes(x = -0.75+1*cos(seq(0,2*pi,length.out=100)), -->
<!--                    y = 2.25+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[2], -->
<!--                alpha = 0.3) +  -->
<!--   # Unfavorable Outcome -->
<!--   geom_polygon(aes(x = 0.75+1*cos(seq(0,2*pi,length.out=100)), -->
<!--                    y = 2.25+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[3], -->
<!--                alpha = 0.3) +  -->
<!--   annotate(geom = "text", x = 1.5, y = 3, hjust = 0, label = "Unfavorable Outcome", size = 5) +  -->
<!--   annotate(geom = "text", x = -1.5, y = 3, hjust = 1, label = "Ranking", size = 5) +  -->
<!--   annotate(geom = "text", x = 0, y = 0, vjust = 1.1, label = "TPP", size = 5) +  -->
<!--   coord_fixed(xlim = c(-3,3), -->
<!--               ylim = c(-0.5, 3.5)) + -->
<!--   annotate(geom = "text", x = 0.75, y = 2.25, label = round(100*p_df_2$only.relapse, 1), size = 5) + -->
<!--   annotate(geom = "text", x = -0.75, y = 2.25, label = round(100*p_df_2$only.rank, 1), size = 5) + -->
<!--   annotate(geom = "text", x = 0, y = 1, label = round(100*p_df_2$only.TPP, 1), size = 5) + -->
<!--   annotate(geom = "text", x = -0.375, y = 1.55, hjust = 1, label = round(100*p_df_2$agree.TPP.rank, 1)) + -->
<!--   annotate(geom = "text", x = 0.375, y = 1.55, hjust = 0, label = round(100*p_df_2$agree.relapse.TPP, 3)) + -->
<!--   annotate(geom = "text", x = 0, y = 1.85, label = round(100*p_df_2$agree.all, 1)) + -->
<!--   annotate(geom = "text", x = 0, y = 2.25, label = round(100*p_df_2$agree.relapse.rank, 1)) + -->
<!--   ggpubr::theme_pubr() +  -->
<!--   labs(caption = paste0("Desirable regimens missed: ", round(p_df_2$p.missed*100, 2), "%")) + -->
<!--   theme(axis.line = element_blank(), -->
<!--         axis.text = element_blank(), -->
<!--         axis.title = element_blank(), -->
<!--         axis.ticks = element_blank(), -->
<!--         plot.title = element_text(hjust = 0.5)) +  -->
<!--   ggtitle("10% Relative Slope, TTP") -->

<!-- p3 <- ggplot() +  -->
<!--   # TPP -->
<!--   geom_polygon(aes(x = 0+1*cos(seq(0,2*pi,length.out=100)),  -->
<!--                    y = 1+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[1], -->
<!--                alpha = 0.3) +  -->
<!--   # Ranking -->
<!--   geom_polygon(aes(x = -0.75+1*cos(seq(0,2*pi,length.out=100)), -->
<!--                    y = 2.25+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[2], -->
<!--                alpha = 0.3) +  -->
<!--   # Unfavorable Outcome -->
<!--   geom_polygon(aes(x = 0.75+1*cos(seq(0,2*pi,length.out=100)), -->
<!--                    y = 2.25+1*sin(seq(0,2*pi,length.out=100))), -->
<!--                fill = ucsf_col_pal[3], -->
<!--                alpha = 0.3) +  -->
<!--   annotate(geom = "text", x = 1.5, y = 3, hjust = 0, label = "Unfavorable Outcome", size = 5) +  -->
<!--   annotate(geom = "text", x = -1.5, y = 3, hjust = 1, label = "Ranking", size = 5) +  -->
<!--   annotate(geom = "text", x = 0, y = 0, vjust = 1.1, label = "TPP", size = 5) +  -->
<!--   coord_fixed(xlim = c(-3,3), -->
<!--               ylim = c(-0.5, 3.5)) + -->
<!--   annotate(geom = "text", x = 0.75, y = 2.25, label = round(100*p_df_3$only.relapse, 1), size = 5) + -->
<!--   annotate(geom = "text", x = -0.75, y = 2.25, label = round(100*p_df_3$only.rank, 1), size = 5) + -->
<!--   annotate(geom = "text", x = 0, y = 1, label = round(100*p_df_3$only.TPP, 1), size = 5) + -->
<!--   annotate(geom = "text", x = -0.375, y = 1.55, hjust = 1, label = round(100*p_df_3$agree.TPP.rank, 1)) + -->
<!--   annotate(geom = "text", x = 0.375, y = 1.55, hjust = 0, label = round(100*p_df_3$agree.relapse.TPP, 1)) + -->
<!--   annotate(geom = "text", x = 0, y = 1.85, label = round(100*p_df_3$agree.all, 1)) + -->
<!--   annotate(geom = "text", x = 0, y = 2.25, label = round(100*p_df_3$agree.relapse.rank, 1)) + -->
<!--   ggpubr::theme_pubr() +  -->
<!--   labs(caption = paste0("Desirable regimens missed: ", round(p_df_3$p.missed*100, 2), "%")) + -->
<!--   theme(axis.line = element_blank(), -->
<!--         axis.text = element_blank(), -->
<!--         axis.title = element_blank(), -->
<!--         axis.ticks = element_blank(), -->
<!--         plot.title = element_text(hjust = 0.5)) +  -->
<!--   ggtitle("20% Relative Slope, TTP") -->

<!-- ggpubr::ggarrange(p1, p2, p3, nrow = 1) -->
<!-- # desirable regimens (relapse) -->
<!-- # prop stopped relapse, prop GO/Continue -->
<!-- ``` -->

<!-- ```{r eval = FALSE} -->
<!-- ggsave(filename = here("graphs", "simulation-results", "random-intercept-random-slope", -->
<!--                               paste0(Sys.Date(), "_venn-diagram_all-together_desirable-nk30.png")), -->
<!--        height = 5, -->
<!--        width = 12,  -->
<!--        units = "in", -->
<!--        device = "png") -->
<!-- ``` -->

### New Attempt

```{r}
######################
# Decision bar plot
######################
library(ggpattern)

data_shape_function <- function(relapse_data, relapse_regimen, tpp_data, ranking_data, nk_choice){
  # Relapses
  r1 <- relapse_data %>% # Situation 1: Regimen 2 - Sub-optimal, Regimen 3 - minimal, Regimen 4 - minimal, Regimen 5 - desirable
    filter(ttp.condition == "highlow", regimen == relapse_regimen) %>%  # TTP did not play a role in simulating relapse data. Selection of ttp condition is irrelevant to the relapses counted. 
    dplyr::select(-regimen, -ttp.condition)
  
  # TPP Decision
  tpp1 <- tpp_data %>% # -10% slope
    filter(Regimen == "Regimen 1", nk == nk_choice) %>% # indexing sets control at 0
    dplyr::select(-Regimen)
  tpp2 <- tpp_data %>% # 10% slope
    filter(Regimen == "Regimen 2", nk == nk_choice) %>% # indexing sets control at 0
    dplyr::select(-Regimen)
  tpp3 <- tpp_data %>% # 35% slope
    filter(Regimen == "Regimen 3", nk == nk_choice) %>% # indexing sets control at 0
    dplyr::select(-Regimen)
  tpp4 <- tpp_data %>% # 40% slope
    filter(Regimen == "Regimen 4", nk == nk_choice) %>% # indexing sets control at 0
    dplyr::select(-Regimen)
  
  # Ranking
  rank1 <- map_dfr(filter(ranking_data, nk == nk_choice),
                   ~.x, .id = "sim") %>% 
    filter(regimen == "arm2") %>% # -10% slope
    dplyr::select(-regimen)
  rank2 <- map_dfr(filter(ranking_data, nk == nk_choice),
                   ~.x, .id = "sim") %>% 
    filter(regimen == "arm3") %>% # 10% slope
    dplyr::select(-regimen)
  rank3 <- map_dfr(filter(ranking_data, nk == nk_choice),
                   ~.x, .id = "sim") %>% 
    filter(regimen == "arm4") %>% # 35% slope
    dplyr::select(-regimen)
  rank4 <- map_dfr(filter(ranking_data, nk == nk_choice),
                   ~.x, .id = "sim") %>% 
    filter(regimen == "arm5") %>% # 40% slope
    dplyr::select(-regimen)
  
  out1 <- full_join(
    full_join(r1, tpp1), rank1) %>% 
    mutate(true.slope = "-10%",
           true.relapse = "sub-optimal",
           nk = nk_choice)
  out2 <- full_join(
    full_join(r1, tpp2), rank2) %>% 
    mutate(true.slope = "10%",
           true.relapse = "sub-optimal",
           nk = nk_choice)
  out3 <- full_join(
    full_join(r1, tpp3), rank3) %>% 
    mutate(true.slope = "35%",
           true.relapse = "sub-optimal",
           nk = nk_choice)
  out4 <- full_join(
    full_join(r1, tpp4), rank4) %>% 
    mutate(true.slope = "40%",
           true.relapse = "sub-optimal",
           nk = nk_choice)
  
  out <- bind_rows(out1, out2, out3, out4)
  return(out)
}

d20 <- data_shape_function(relapse_data = s95.sit1.20,
                           relapse_regimen = "2", # Sub-optimal
                           tpp_data = decisions$decisions_highlow,
                           ranking_data = ranking_probabilities$highlow_probabilities,
                           nk_choice = 20)
d30 <- data_shape_function(relapse_data = s95.sit1.30, 
                           relapse_regimen = "2", # Sub-optimal
                           tpp_data = decisions$decisions_highlow,
                           ranking_data = ranking_probabilities$highlow_probabilities,
                           nk_choice = 30)
d40 <- data_shape_function(relapse_data = s95.sit1.40, 
                           relapse_regimen = "2", # Sub-optimal
                           tpp_data = decisions$decisions_highlow,
                           ranking_data = ranking_probabilities$highlow_probabilities,
                           nk_choice = 40)
d60 <- data_shape_function(relapse_data = s95.sit1.60, 
                           relapse_regimen = "2", # Sub-optimal
                           tpp_data = decisions$decisions_highlow,
                           ranking_data = ranking_probabilities$highlow_probabilities,
                           nk_choice = 60)
d80 <- data_shape_function(relapse_data = s95.sit1.80, 
                           relapse_regimen = "2", # Sub-optimal
                           tpp_data = decisions$decisions_highlow,
                           ranking_data = ranking_probabilities$highlow_probabilities,
                           nk_choice = 80)

p_suboptimal <- bind_rows(d20, d30, d40)  %>% #, d60, d80) %>% 
  mutate(decision = case_when((n_relapse_interim1 < 2 & Decision == "GO" & p.subset.2 >= 0.5) ~ "GO",
                              ((n_relapse_interim1 >= 2) | (Decision == "NO-GO")) ~ "NO-GO",
                              TRUE ~ "Continue")) %>% 
  mutate(decision = factor(decision, levels = c("NO-GO", "Continue", "GO"))) %>% 
  mutate(decision2 = case_when((decision == "NO-GO" & n_relapse_interim1 >= 2 & Decision != "NO-GO") ~ "Unfavorable outcome only",
                               (decision == "NO-GO" & n_relapse_interim1 < 2 & Decision == "NO-GO") ~ "TPP only")) %>% 
  group_by(true.slope, nk, decision, decision2) %>% 
  mutate(decision2 = ifelse(is.na(decision2), "other", decision2)) %>% 
  mutate(decision2 = factor(decision2, levels = c("other", "Unfavorable outcome only", "TPP only"))) %>% 
  summarise(n = n()) %>% 
  group_by(true.slope, nk) %>% 
  mutate(prop = n/sum(n)) %>% 
  ggplot(aes(x = as.factor(nk), y = prop)) + 
  geom_bar_pattern(aes(fill = decision,
                       pattern = decision2),
                   pattern_color = "white",
                   pattern_fill = "white",
                   # pattern_alpha = 0.5,
                   stat = "identity") + 
  scale_pattern_manual(values = c("none","stripe","circle"),
                       guide = "none") +
  facet_wrap(~true.slope, nrow = 1) + 
  scale_y_continuous("Decision Probability",
                     breaks = seq(0,1,by = 0.1),
                     labels = seq(0,1,by = 0.1)) +
  scale_fill_manual(values = c("red", ucsf_col_pal[8], ucsf_col_pal[4]),
                    breaks = c("NO-GO", "Continue", "GO"),
                    labels = c("NO-GO", "Continue", "GO")) +
  xlab(TeX("$n_k$")) + 
  # ggtitle("", subtitle = TeX("$\\theta_{MAV} = 0%, \\theta_{TV} = 20%, \\tau_{MAV} = \\tau_{TV} = 0.025$")) +
  ggpubr::theme_pubr() + 
  theme(legend.position = "bottom",
        legend.title = element_blank(),
        axis.title.x = element_blank())

bind_rows(d20, d30, d40)  %>% 
  mutate(decision = case_when((n_relapse_interim1 < 2 & Decision == "GO" & p.subset.2 >= 0.5) ~ "GO",
                              ((n_relapse_interim1 >= 2) | (Decision == "NO-GO")) ~ "NO-GO",
                              TRUE ~ "Continue")) %>% 
  mutate(decision = factor(decision, levels = c("NO-GO", "Continue", "GO"))) %>% 
  mutate(decision2 = case_when((decision == "NO-GO" & n_relapse_interim1 >= 2 & Decision != "NO-GO") ~ "Unfavorable outcome only",
                               (decision == "NO-GO" & n_relapse_interim1 < 2 & Decision == "NO-GO") ~ "TPP only")) %>% 
  group_by(true.slope, nk, decision, decision2) %>% 
  mutate(decision2 = ifelse(is.na(decision2), "other", decision2)) %>% 
  mutate(decision2 = factor(decision2, levels = c("other", "Unfavorable outcome only", "TPP only"))) %>% 
  summarise(n = n()) %>% 
  group_by(true.slope, nk) %>% 
  mutate(prop = n/sum(n)) %>% 
  transmute(true.slope, nk, decision, Criterion = decision2, `N (%)` = paste0(n, " (", round(100*prop, 1), ")")) %>% 
  pivot_wider(names_from = decision, values_from = `N (%)`) %>%
  kable(caption = "Sub-optimal relapse rate (10%).") %>% 
  kable_styling() %>% 
  pack_rows(group_label = "Relative TTP slope: -10%",
            start_row = 1,
            end_row = 9) %>% 
  pack_rows(group_label = "Relative TTP slope: 10%",
            start_row = 10,
            end_row = 18) %>% 
  pack_rows(group_label = "Relative TTP slope: 35%",
            start_row = 19,
            end_row = 25) %>% 
  pack_rows(group_label = "Relative TTP slope: 40%",
            start_row = 26,
            end_row = 33)

# p_suboptimal

# Minimal
d20 <- data_shape_function(relapse_data = s95.sit1.20,
                           relapse_regimen = "3", # Minimal
                           tpp_data = decisions$decisions_highlow,
                           ranking_data = ranking_probabilities$highlow_probabilities,
                           nk_choice = 20)
d30 <- data_shape_function(relapse_data = s95.sit1.30, 
                           relapse_regimen = "3", # Minimal
                           tpp_data = decisions$decisions_highlow,
                           ranking_data = ranking_probabilities$highlow_probabilities,
                           nk_choice = 30)
d40 <- data_shape_function(relapse_data = s95.sit1.40, 
                           relapse_regimen = "3", # Minimal
                           tpp_data = decisions$decisions_highlow,
                           ranking_data = ranking_probabilities$highlow_probabilities,
                           nk_choice = 40)
d60 <- data_shape_function(relapse_data = s95.sit1.60, 
                           relapse_regimen = "3", # Minimal
                           tpp_data = decisions$decisions_highlow,
                           ranking_data = ranking_probabilities$highlow_probabilities,
                           nk_choice = 60)
d80 <- data_shape_function(relapse_data = s95.sit1.80, 
                           relapse_regimen = "3", # Minimal
                           tpp_data = decisions$decisions_highlow,
                           ranking_data = ranking_probabilities$highlow_probabilities,
                           nk_choice = 80)

p_minimal <- bind_rows(d20, d30, d40)  %>% #, d60, d80) %>% 
  mutate(decision = case_when((n_relapse_interim1 < 2 & Decision == "GO" & p.subset.2 >= 0.5) ~ "GO",
                              ((n_relapse_interim1 >= 2) | (Decision == "NO-GO")) ~ "NO-GO",
                              TRUE ~ "Continue")) %>% 
  mutate(decision = factor(decision, levels = c("NO-GO", "Continue", "GO"))) %>% 
  mutate(decision2 = case_when((decision == "NO-GO" & n_relapse_interim1 >= 2 & Decision != "NO-GO") ~ "Unfavorable outcome only",
                               (decision == "NO-GO" & n_relapse_interim1 < 2 & Decision == "NO-GO") ~ "TPP only")) %>% 
  group_by(true.slope, nk, decision, decision2) %>% 
  mutate(decision2 = ifelse(is.na(decision2), "other", decision2)) %>% 
  mutate(decision2 = factor(decision2, levels = c("other", "Unfavorable outcome only", "TPP only"))) %>% 
  summarise(n = n()) %>% 
  group_by(true.slope, nk) %>% 
  mutate(prop = n/sum(n)) %>% 
  ggplot(aes(x = as.factor(nk), y = prop)) + 
  geom_bar_pattern(aes(fill = decision,
                       pattern = decision2),
                   pattern_color = "white",
                   pattern_fill = "white",
                   # pattern_alpha = 0.5,
                   stat = "identity") + 
  scale_pattern_manual(values = c("none","stripe","circle"),
                       guide = "none") +
  facet_wrap(~true.slope, nrow = 1) + 
  scale_y_continuous("Decision Probability",
                     breaks = seq(0,1,by = 0.1),
                     labels = seq(0,1,by = 0.1)) +
  scale_fill_manual(values = c("red", ucsf_col_pal[8], ucsf_col_pal[4]),
                    breaks = c("NO-GO", "Continue", "GO"),
                    labels = c("NO-GO", "Continue", "GO")) +
  xlab(TeX("$n_k$")) + 
  # ggtitle("", subtitle = TeX("$\\theta_{MAV} = 0%, \\theta_{TV} = 20%, \\tau_{MAV} = \\tau_{TV} = 0.025$")) +
  ggpubr::theme_pubr() + 
  theme(legend.position = "bottom",
        legend.title = element_blank(),
        axis.title.x = element_blank())
# p_minimal

# Desirable
d20 <- data_shape_function(relapse_data = s95.sit1.20,
                           relapse_regimen = "5", # Desirable
                           tpp_data = decisions$decisions_highlow,
                           ranking_data = ranking_probabilities$highlow_probabilities,
                           nk_choice = 20)
d30 <- data_shape_function(relapse_data = s95.sit1.30, 
                           relapse_regimen = "5", # Desirable
                           tpp_data = decisions$decisions_highlow,
                           ranking_data = ranking_probabilities$highlow_probabilities,
                           nk_choice = 30)
d40 <- data_shape_function(relapse_data = s95.sit1.40, 
                           relapse_regimen = "5", # Desirable
                           tpp_data = decisions$decisions_highlow,
                           ranking_data = ranking_probabilities$highlow_probabilities,
                           nk_choice = 40)
d60 <- data_shape_function(relapse_data = s95.sit1.60, 
                           relapse_regimen = "5", # Desirable
                           tpp_data = decisions$decisions_highlow,
                           ranking_data = ranking_probabilities$highlow_probabilities,
                           nk_choice = 60)
d80 <- data_shape_function(relapse_data = s95.sit1.80, 
                           relapse_regimen = "5", # Desirable
                           tpp_data = decisions$decisions_highlow,
                           ranking_data = ranking_probabilities$highlow_probabilities,
                           nk_choice = 80)

p_desirable <- bind_rows(d20, d30, d40)  %>% #, d60, d80) %>% 
  mutate(decision = case_when((n_relapse_interim1 < 2 & Decision == "GO" & p.subset.2 >= 0.5) ~ "GO",
                              ((n_relapse_interim1 >= 2) | (Decision == "NO-GO")) ~ "NO-GO",
                              TRUE ~ "Continue")) %>% 
  mutate(decision = factor(decision, levels = c("NO-GO", "Continue", "GO"))) %>% 
  mutate(decision2 = case_when((decision == "NO-GO" & n_relapse_interim1 >= 2 & Decision != "NO-GO") ~ "Unfavorable outcome only",
                               (decision == "NO-GO" & n_relapse_interim1 < 2 & Decision == "NO-GO") ~ "TPP only")) %>% 
  group_by(true.slope, nk, decision, decision2) %>% 
  mutate(decision2 = ifelse(is.na(decision2), "other", decision2)) %>% 
  mutate(decision2 = factor(decision2, levels = c("other", "Unfavorable outcome only", "TPP only"))) %>% 
  summarise(n = n()) %>% 
  group_by(true.slope, nk) %>% 
  mutate(prop = n/sum(n)) %>% 
  ggplot(aes(x = as.factor(nk), y = prop)) + 
  geom_bar_pattern(aes(fill = decision,
                       pattern = decision2),
                   pattern_color = "white",
                   pattern_fill = "white",
                   # pattern_alpha = 0.5,
                   stat = "identity") + 
  scale_pattern_manual(values = c("none","stripe","circle"),
                       guide = "none") +
  facet_wrap(~true.slope, nrow = 1) + 
  scale_y_continuous("Decision Probability",
                     breaks = seq(0,1,by = 0.1),
                     labels = seq(0,1,by = 0.1)) +
  scale_fill_manual(values = c("red", ucsf_col_pal[8], ucsf_col_pal[4]),
                    breaks = c("NO-GO", "Continue", "GO"),
                    labels = c("NO-GO", "Continue", "GO")) +
  xlab(TeX("$n_k$")) + 
  # ggtitle("", subtitle = TeX("$\\theta_{MAV} = 0%, \\theta_{TV} = 20%, \\tau_{MAV} = \\tau_{TV} = 0.025$")) +
  ggpubr::theme_pubr() + 
  theme(legend.position = "bottom",
        legend.title = element_blank())

bind_rows(d20, d30, d40)  %>% #, d60, d80) %>% 
  mutate(decision = case_when((n_relapse_interim1 < 2 & Decision == "GO" & p.subset.2 >= 0.5) ~ "GO",
                              ((n_relapse_interim1 >= 2) | (Decision == "NO-GO")) ~ "NO-GO",
                              TRUE ~ "Continue")) %>% 
  mutate(decision = factor(decision, levels = c("NO-GO", "Continue", "GO"))) %>% 
  mutate(decision2 = case_when((decision == "NO-GO" & n_relapse_interim1 >= 2 & Decision != "NO-GO") ~ "Unfavorable outcome only",
                               (decision == "NO-GO" & n_relapse_interim1 < 2 & Decision == "NO-GO") ~ "TPP only")) %>% 
  group_by(true.slope, nk, decision, decision2) %>% 
  mutate(decision2 = ifelse(is.na(decision2), "other", decision2)) %>% 
  mutate(decision2 = factor(decision2, levels = c("other", "Unfavorable outcome only", "TPP only"))) %>% 
  summarise(n = n()) %>% 
  group_by(true.slope, nk) %>% 
  mutate(prop = n/sum(n)) %>% 
  kable(digits = 3) %>% 
  kable_styling()

# p_desirable
```

```{r fig.height=10, fig.cap="Interim analysis decision probabilities for simulated arms with TTP slope relative to the control as specified in the panels (all corresponding to the `2 Winners` simulation setting) and unfavorable outcome rates of A) 10% (unfavorable), B) 5% (minimal), and C) 2.5% (desirable). Arms are flagged for a GO decision if they meet all the following conditions: fewer than 2 unfavorable outcomes, evidence of meeting the target product profile, and a posterior probability greater than 50% of ranking in the top two arms. A pattern is applied to differentiate the criterion responsible for NO-GO decisions. Arms are flagged for a NO-GO decision if they experience any of the following conditions: 2 or more unfavorable outcomes (stripes), do not have evidence of meeting the target product profile (dots), or meet both conditions (plain). All arms that do not meet the criteria for a GO or NO-GO decision, receive a Continue designation. Results are based on 1,000 simulated datasets per setting."}
p_suboptimal / p_minimal / p_desirable + 
  plot_layout(guides = "collect") + 
  plot_annotation(tag_levels = "A") &
  theme(legend.position = "bottom")
```

```{r}
#| eval: false
ggsave(filename = here("graphs", "submission", "fig-02_panel-oc-full-framework.png"),
       device = "png",
       height = 8,
       width = 8,
       units = "in")
```


## Single Example

```{r relapse-single}
df_relapse_single <- s95.sit1.30 %>% 
  filter(sim == 7, ttp.condition == "even")

t_relapse <- df_relapse_single  
```

```{r ttp-single}
df_single <- mcmc_mods_even_30[[7]] 

# turning estimates into relative, % slopes
df_single$arm2 <- (df_single$arm2 - df_single$arm1)/df_single$arm1
df_single$arm3 <- (df_single$arm3 - df_single$arm1)/df_single$arm1
df_single$arm4 <- (df_single$arm4 - df_single$arm1)/df_single$arm1
df_single$arm5 <- (df_single$arm5 - df_single$arm1)/df_single$arm1

t_estimates <- df_single[,2:5] %>% 
  pivot_longer(names_to = "regimen",
               values_to = "cred.est",
               cols = 1:4) %>% 
  group_by(regimen) %>% 
  summarise(est.median = quantile(cred.est, probs = 0.5),
            est.CI.l = quantile(cred.est, probs = 0.025),
            est.CI.u = quantile(cred.est, probs = 0.975)) 
```

```{r}
theta_mav <- 0
theta_tv <- .2
tau_mav <- 0.025
tau_tv <- 0.025

decision_function <- function(theta_mav, theta_tv, tau_mav, tau_tv, mcmc_chain){
  out <- mcmc_chain %>% 
    pivot_longer(names_to = "regimen",
                 values_to = "cred.est",
                 cols = everything()) %>% 
    group_by(regimen) %>% 
    summarise(est.CI.l = quantile(cred.est, probs = tau_mav),
              est.CI.u = quantile(cred.est, probs = 1-tau_tv))
  
  output <- out %>% 
    mutate(decision = case_when(est.CI.u <= theta_tv ~ "NO-GO",
                                (est.CI.u > theta_tv & est.CI.l <= theta_mav) ~ "Continue",
                                (est.CI.u > theta_tv & est.CI.l > theta_mav) ~ "GO"))
  
  posterior.probs <- mcmc_chain %>% 
    pivot_longer(names_to = "regimen",
                 values_to = "cred.est",
                 cols = everything()) %>% 
    group_by(regimen) %>% 
    summarise(p.theta.k.greater.theta.tv = mean(cred.est > theta_tv),
              p.theta.k.greater.theta.mav = mean(cred.est > theta_mav))
  
  output <- full_join(output, posterior.probs)
  return(output)
}

t_tpp <- decision_function(theta_mav = theta_mav, theta_tv = theta_tv, tau_mav = tau_mav, tau_tv = tau_tv, mcmc_chain = df_single[,2:5]) 
```

```{r}
t_rank <- mcmc_rank_function(df_single) 
```

```{r}
t_gcontrol <- df_single[,2:5] %>% 
  pivot_longer(cols = everything(),
               names_to = "regimen", 
               values_to = "cred.est") %>% 
  group_by(regimen) %>% 
  summarise(p.greater.than.control = mean(cred.est > 0))  

```

```{r}
t_relapse %>% 
  mutate(regimen = paste0("arm", regimen)) %>% 
  full_join(t_estimates) %>% 
  full_join(t_tpp) %>% 
  full_join(t_gcontrol) %>% 
  full_join(t_rank) %>% 
  mutate(regimen = str_remove(regimen, "arm"),
         Duration = c(26,rep(16,4)),
         nk = 30) %>% 
  dplyr::select(Regimen = regimen, Duration = Duration, `No. patients` = nk, `No. relapses` = n_relapse_interim1, `$\\hat{\\theta}_{0.5}$` = est.median, `$\\hat{\\theta}_{0.025}$` = est.CI.l, `$\\hat{\\theta}_{0.975}$` = est.CI.u, `$P(\\theta_k > \\theta_{MAV})$`=p.theta.k.greater.theta.mav, `$P(\\theta_k > \\theta_{TV})$`=p.theta.k.greater.theta.tv, `TPP decision` = decision, `$\\hat{\\psi}_1$` = p.greater.than.control, `$\\hat{\\psi}_2$` = p.subset.1, `$\\hat{\\psi}_3$` = p.subset.2) %>% 
  kable(digits = 3,
        caption = "Interim results from a single simulated phase 2B study with thirty partients per regimen. The target product profile (TPP) assumes $\\theta_{MAV} = 0, \\theta_{TV} = 20, \\tau_{MAV} = \\tau_{TV} = 0.025$.") %>% 
  kable_styling() %>% 
  add_header_above(c(" " = 2, "Interim 1" = 11))
```
